// ============================================================================
// GEMSIM: DEFAULT SEED SCENARIOS
// Preloaded Enterprise Case Studies for Immediate Playability
// ============================================================================

import { Scenario } from '../types/index.js';

export const SEED_SCENARIOS: Scenario[] = [
  {
    id: 'scen-fintech-neotitan',
    title: 'Project NeoTitan: Core Banking Modernization',
    industry: 'Financial Services & Digital Banking',
    domain: 'IT',
    language: 'en',
    difficulty: 'INTERMEDIATE',
    description: 'Lead NeoTitan Bank through a 4-quarter modernization saga. Balance rapid neobank feature delivery with legacy mainframe decoupling, PCI-DSS compliance, and zero-downtime reliability.',
    businessContext: 'NeoTitan Bank serves 12M retail and commercial accounts. Core transaction clearing runs on a 25-year-old COBOL mainframe monolith. A competitor neobank is acquiring 150K users/month with instant virtual card issuing, while NeoTitan takes 4 days to settle transactions. Technical debt has reached 72%, and maintenance consumes 68% of IT budget.',
    baselineMetrics: {
      tco: 2400,
      budgetRemaining: 1500,
      opEx: 580,
      capExSpent: 400,
      technicalDebtIndex: 72,
      deliveryVelocity: 44,
      stakeholderTrust: 52,
      resilienceIndex: 48,
      complianceScore: 65,
      modernizedNodesCount: 1,
    },
    winLossConditions: {
      maxTechnicalDebtIndex: 45,
      minStakeholderTrustAvg: 60,
      minDeliveryVelocity: 68,
      minResilienceIndex: 72,
      maxTCOBudget: 4800,
      targetCapabilitiesModernized: 4,
    },
    totalRounds: 4,
    topology: {
      nodes: [
        {
          id: 'node-biz-app',
          name: 'Mobile Banking & Card Controls',
          layer: 'BUSINESS',
          description: 'Customer digital experience for iOS, Android, and Web portals.',
          health: 78,
          technicalDebt: 28,
          criticalPath: true,
          costPerRound: 55,
          position: { x: -6, y: 5, z: 0 },
          status: 'HEALTHY',
          dependencies: ['node-api-gw'],
          telemetry: { latencyMs: 45, throughputRps: 2800, errorRatePercent: 0.1, failureRisk: 16 },
        },
        {
          id: 'node-biz-lending',
          name: 'Commercial Lending & Risk Portal',
          layer: 'BUSINESS',
          description: 'Underwriting and commercial credit approvals.',
          health: 62,
          technicalDebt: 58,
          criticalPath: false,
          costPerRound: 65,
          position: { x: 6, y: 5, z: 0 },
          status: 'DEGRADED',
          dependencies: ['node-api-gw', 'node-legacy-core'],
          telemetry: { latencyMs: 320, throughputRps: 450, errorRatePercent: 1.4, failureRisk: 42 },
        },
        {
          id: 'node-api-gw',
          name: 'Zero-Trust API Gateway',
          layer: 'APPLICATION',
          description: 'Identity tokenization, rate limiting, and mTLS proxy.',
          health: 82,
          technicalDebt: 22,
          criticalPath: true,
          costPerRound: 40,
          position: { x: -4, y: 2, z: 0 },
          status: 'HEALTHY',
          dependencies: ['node-legacy-core', 'node-mod-services'],
          telemetry: { latencyMs: 14, throughputRps: 4200, errorRatePercent: 0.02, failureRisk: 10 },
        },
        {
          id: 'node-legacy-core',
          name: 'Mainframe Core Banking Monolith',
          layer: 'APPLICATION',
          description: 'Single monolithic ledger handling account balances, interest calculations, and batch clearing.',
          health: 38,
          technicalDebt: 82,
          criticalPath: true,
          costPerRound: 180,
          position: { x: 0, y: 2, z: 0 },
          status: 'CRITICAL',
          dependencies: ['node-db-mainframe', 'node-infra-onprem'],
          telemetry: { latencyMs: 820, throughputRps: 650, errorRatePercent: 4.2, failureRisk: 88 },
        },
        {
          id: 'node-mod-services',
          name: 'Payments Microservices (Strangler)',
          layer: 'APPLICATION',
          description: 'Decoupled domain services handling instant P2P payments and push notifications.',
          health: 88,
          technicalDebt: 15,
          criticalPath: false,
          costPerRound: 55,
          position: { x: 5, y: 2, z: 0 },
          status: 'MODERNIZED',
          dependencies: ['node-kafka-bus', 'node-infra-cloud'],
          telemetry: { latencyMs: 25, throughputRps: 3100, errorRatePercent: 0.05, failureRisk: 12 },
        },
        {
          id: 'node-db-mainframe',
          name: 'Hierarchical DB2 Mainframe Storage',
          layer: 'DATA',
          description: 'Legacy relational database with table locks and batch-night freeze windows.',
          health: 44,
          technicalDebt: 76,
          criticalPath: true,
          costPerRound: 110,
          position: { x: -2, y: -2, z: 0 },
          status: 'CRITICAL',
          dependencies: ['node-infra-onprem'],
          telemetry: { latencyMs: 460, throughputRps: 950, errorRatePercent: 2.8, failureRisk: 74 },
        },
        {
          id: 'node-kafka-bus',
          name: 'Kafka Real-Time Financial Ledger',
          layer: 'DATA',
          description: 'Distributed immutable event log for real-time auditability and ledger streaming.',
          health: 94,
          technicalDebt: 10,
          criticalPath: false,
          costPerRound: 45,
          position: { x: 4, y: -2, z: 0 },
          status: 'MODERNIZED',
          dependencies: ['node-infra-cloud'],
          telemetry: { latencyMs: 8, throughputRps: 8400, errorRatePercent: 0.01, failureRisk: 6 },
        },
        {
          id: 'node-infra-onprem',
          name: 'Tier-4 Legacy On-Premises Datacenter',
          layer: 'INFRASTRUCTURE',
          description: 'Fixed capacity server racks, annual hardware licensing, high power costs.',
          health: 56,
          technicalDebt: 64,
          criticalPath: true,
          costPerRound: 120,
          position: { x: -3, y: -5, z: 0 },
          status: 'DEGRADED',
          dependencies: [],
          telemetry: { latencyMs: 95, throughputRps: 3800, errorRatePercent: 0.8, failureRisk: 48 },
        },
        {
          id: 'node-infra-cloud',
          name: 'Cloud Kubernetes Multi-Zone Mesh',
          layer: 'INFRASTRUCTURE',
          description: 'Elastic multi-region infrastructure with automated failover and sub-second auto-scaling.',
          health: 92,
          technicalDebt: 12,
          criticalPath: false,
          costPerRound: 70,
          position: { x: 3, y: -5, z: 0 },
          status: 'MODERNIZED',
          dependencies: [],
          telemetry: { latencyMs: 18, throughputRps: 9200, errorRatePercent: 0.02, failureRisk: 8 },
        },
      ],
      edges: [
        { id: 'e1', fromId: 'node-biz-app', toId: 'node-api-gw', protocol: 'HTTPS/REST', bandwidthMbps: 2500, status: 'NORMAL', latencyMs: 20 },
        { id: 'e2', fromId: 'node-biz-lending', toId: 'node-legacy-core', protocol: 'MQ Series', bandwidthMbps: 350, status: 'BOTTLENECK', latencyMs: 340 },
        { id: 'e3', fromId: 'node-api-gw', toId: 'node-legacy-core', protocol: 'SNA / TCP Gateway', bandwidthMbps: 400, status: 'BOTTLENECK', latencyMs: 420 },
        { id: 'e4', fromId: 'node-api-gw', toId: 'node-mod-services', protocol: 'gRPC HTTP/2', bandwidthMbps: 3000, status: 'OPTIMIZED', latencyMs: 12 },
        { id: 'e5', fromId: 'node-legacy-core', toId: 'node-db-mainframe', protocol: 'Internal Bus', bandwidthMbps: 600, status: 'BOTTLENECK', latencyMs: 380 },
        { id: 'e6', fromId: 'node-mod-services', toId: 'node-kafka-bus', protocol: 'Kafka Wire', bandwidthMbps: 4500, status: 'OPTIMIZED', latencyMs: 6 },
        { id: 'e7', fromId: 'node-db-mainframe', toId: 'node-infra-onprem', protocol: 'SAN Fiber', bandwidthMbps: 1200, status: 'NORMAL', latencyMs: 35 },
        { id: 'e8', fromId: 'node-kafka-bus', toId: 'node-infra-cloud', protocol: 'Cloud Fabric', bandwidthMbps: 8000, status: 'OPTIMIZED', latencyMs: 4 },
      ],
    },
    stakeholders: [
      {
        id: 'sh-cfo-marcus',
        name: 'Marcus Vance',
        title: 'Chief Financial Officer',
        role: 'Capital Allocation & Shareholder Returns',
        avatar: '💼',
        personality: 'Analytical, laser-focused on quarterly margins and OpEx depreciation.',
        bias: 'Demands immediate quantifiable ROI on all IT expenditures.',
        hiddenAgenda: 'Preparing the bank for a secondary debt offering; cannot tolerate sudden OpEx spikes.',
        negotiationTolerance: 50,
        baseTrust: 55,
        decisionWeights: { financialAcumen: 0.65, deliverySpeed: 0.1, architecturalRigor: 0.15, regulatoryCompliance: 0.1 },
        sampleDialogue: {
          greeting: 'Explain to me why we are spending $400K on refactoring when our return on equity is down 20 bps.',
          resistance: 'I will not approve speculative architectural bets without binding OpEx reduction targets.',
          concession: 'Commit to decommissioning legacy mainframe MIPS by Q4, and I will release modernization capital.',
        },
      },
      {
        id: 'sh-vp-priya',
        name: 'Priya Patel',
        title: 'VP of Digital Banking',
        role: 'Product Velocity & Customer Acquisition',
        avatar: '🚀',
        personality: 'Fast-moving, aggressive, customer obsessed.',
        bias: 'Views architectural reviews and governance gates as bureaucratic excuses for delay.',
        hiddenAgenda: 'Needs to launch instantaneous credit line increases before Q3 earnings call to hit executive incentive bonus.',
        negotiationTolerance: 40,
        baseTrust: 60,
        decisionWeights: { financialAcumen: 0.1, deliverySpeed: 0.7, architecturalRigor: 0.05, regulatoryCompliance: 0.15 },
        sampleDialogue: {
          greeting: 'Our customer churn is at 4.2% because the mobile app takes 8 seconds to load accounts.',
          resistance: 'We cannot pause commercial features for another database migration sprint.',
          concession: 'If you isolate the payment service so my squads can deploy weekly, I will advocate for your budget.',
        },
      },
      {
        id: 'sh-cto-elena',
        name: 'Dr. Elena Rostova',
        title: 'Chief Enterprise Architect',
        role: 'Systems Architecture & Technical Governance',
        avatar: '🛡️',
        personality: 'Principled, rigorous, guardian of long-term engineering health.',
        bias: 'Categorically opposes point-to-point shortcuts and dirty database hooks.',
        hiddenAgenda: 'Wants to establish domain-driven design and event sourcing as standard bank policy.',
        negotiationTolerance: 65,
        baseTrust: 65,
        decisionWeights: { financialAcumen: 0.15, deliverySpeed: 0.1, architecturalRigor: 0.6, regulatoryCompliance: 0.15 },
        sampleDialogue: {
          greeting: 'Bypassing the architecture review board is why we had an 8-hour outage last quarter.',
          resistance: 'Writing directly to the core DB2 tables will corrupt the balance reconciliation ledger.',
          concession: 'If you implement the strangler fig pattern with strict schema contracts, I will expedite review approval.',
        },
      },
      {
        id: 'sh-cso-arthur',
        name: 'Arthur Sterling',
        title: 'Chief Risk & Compliance Officer',
        role: 'Regulatory Adherence & Information Security',
        avatar: '⚖️',
        personality: 'Methodical, audit-sensitive, cautious.',
        bias: 'Prioritizes compliance certifications and data privacy over delivery speed.',
        hiddenAgenda: 'Under direct scrutiny by regulatory agency after industry-wide data leak audit.',
        negotiationTolerance: 45,
        baseTrust: 50,
        decisionWeights: { financialAcumen: 0.1, deliverySpeed: 0.05, architecturalRigor: 0.25, regulatoryCompliance: 0.6 },
        sampleDialogue: {
          greeting: 'Regulatory penalties are not hypothetical. They are existential.',
          resistance: 'This cloud migration proposal does not provide hardware encryption isolation for payment secrets.',
          concession: 'Incorporate HSM tokenization and audit logging, and I will sign off on the production clearance.',
        },
      },
    ],
    roundEvents: [
      {
        roundNumber: 1,
        title: 'Q1: Competitor Neobank Instant-Card Launch',
        description: 'Challenger bank "ApexPay" launched instant virtual cards with zero fx fees, pulling away 80,000 younger depositors. Product leadership demands immediate parity.',
        type: 'COMPETITIVE_SURGE',
        severity: 'MEDIUM',
        immediateImpact: { budgetFine: 60, tdiSurge: 6, velocityPenalty: 0 },
        choices: [
          {
            id: 'ev1-shortcut',
            text: 'Hack direct API hooks into the COBOL monolith (Launches in 3 weeks, massive debt)',
            capExImpact: 80,
            tdiImpact: 15,
            velocityImpact: 18,
            trustImpact: { 'sh-vp-priya': 15, 'sh-cto-elena': -15 },
          },
          {
            id: 'ev1-strangler',
            text: 'Deploy an anti-corruption layer & Kafka microservice (4-week delay, sound architecture)',
            capExImpact: 160,
            tdiImpact: -8,
            velocityImpact: -5,
            trustImpact: { 'sh-cto-elena': 14, 'sh-vp-priya': -6, 'sh-cfo-marcus': -4 },
          },
          {
            id: 'ev1-wait',
            text: 'Offer cashback incentives instead of technology changes (Conserves engineering, burns marketing cash)',
            capExImpact: 120,
            tdiImpact: 0,
            velocityImpact: 0,
            trustImpact: { 'sh-cfo-marcus': -10, 'sh-vp-priya': -8 },
          },
        ],
      },
      {
        roundNumber: 2,
        title: 'Q2: Central Bank Regulatory Open Banking Mandate',
        description: 'Banking authorities announce mandatory open-banking API standards with strict 300ms SLA and audit penalties for non-compliance.',
        type: 'AUDIT',
        severity: 'HIGH',
        immediateImpact: { budgetFine: 140, tdiSurge: 0, velocityPenalty: -10 },
        choices: [
          {
            id: 'ev2-modern-gateway',
            text: 'Deploy cloud-native API gateway with Redis rate limiting and automated audit telemetry',
            capExImpact: 210,
            tdiImpact: -12,
            velocityImpact: 10,
            trustImpact: { 'sh-cso-arthur': 20, 'sh-cto-elena': 12, 'sh-cfo-marcus': -8 },
          },
          {
            id: 'ev2-patch-core',
            text: 'Expose legacy MQ endpoints through an unencrypted reverse proxy',
            capExImpact: 70,
            tdiImpact: 12,
            velocityImpact: 0,
            trustImpact: { 'sh-cso-arthur': -18, 'sh-cfo-marcus': 6 },
          },
          {
            id: 'ev2-seek-waiver',
            text: 'Hire regulatory lobbyists to request a 1-year compliance extension',
            capExImpact: 150,
            tdiImpact: 0,
            velocityImpact: 0,
            trustImpact: { 'sh-cso-arthur': -12, 'sh-cfo-marcus': -10 },
          },
        ],
      },
      {
        roundNumber: 3,
        title: 'Q3: Black Friday Transaction Surge & Monolith Deadlock',
        description: 'Simultaneous shopping volume causes DB2 transaction locking. Account balances freeze for 47 minutes during peak evening hours.',
        type: 'CRISIS',
        severity: 'BLACK_SWAN',
        immediateImpact: { budgetFine: 320, tdiSurge: 10, velocityPenalty: -25, downedNodeIds: ['node-legacy-core', 'node-db-mainframe'] },
        choices: [
          {
            id: 'ev3-read-shards',
            text: 'Emergency Strangler: Divert balance read traffic to asynchronous Kafka replicas with circuit breaker',
            capExImpact: 240,
            tdiImpact: -18,
            velocityImpact: 8,
            trustImpact: { 'sh-cto-elena': 18, 'sh-cfo-marcus': -12 },
          },
          {
            id: 'ev3-scale-hardware',
            text: 'Emergency mainframe MIPS lease upgrade (Huge recurring OpEx penalty)',
            capExImpact: 350,
            tdiImpact: 6,
            velocityImpact: -5,
            trustImpact: { 'sh-cfo-marcus': -20, 'sh-vp-priya': 10 },
          },
          {
            id: 'ev3-throttle',
            text: 'Aggressively rate-limit non-essential traffic and queue mobile transactions',
            capExImpact: 50,
            tdiImpact: 2,
            velocityImpact: -18,
            trustImpact: { 'sh-vp-priya': -22, 'sh-cfo-marcus': -6 },
          },
        ],
      },
      {
        roundNumber: 4,
        title: 'Q4: Annual Board Strategy & Modernization Verdict',
        description: 'The Board reviews the bank transformation. Final scorecard evaluates TCO, debt reduction, platform velocity, and reliability.',
        type: 'MARKET_SHIFT',
        severity: 'HIGH',
        immediateImpact: { budgetFine: 0, tdiSurge: 0, velocityPenalty: 0 },
        choices: [
          {
            id: 'ev4-expansion',
            text: 'Showcase modernized microservices and request multi-year cloud transformation tranches',
            capExImpact: 150,
            tdiImpact: -6,
            velocityImpact: 12,
            trustImpact: { 'sh-cfo-marcus': 10, 'sh-vp-priya': 12, 'sh-cto-elena': 15 },
          },
          {
            id: 'ev4-cash-freeze',
            text: 'Implement austerity spending freeze to boast high short-term cash reserves to Wall Street',
            capExImpact: -120,
            tdiImpact: 14,
            velocityImpact: -18,
            trustImpact: { 'sh-cfo-marcus': 20, 'sh-cto-elena': -18, 'sh-vp-priya': -16 },
          },
          {
            id: 'ev4-balanced-close',
            text: 'Maintain existing investment velocity into the next fiscal calendar',
            capExImpact: 0,
            tdiImpact: 0,
            velocityImpact: 0,
            trustImpact: { 'sh-cfo-marcus': 5, 'sh-cto-elena': 5 },
          },
        ],
      },
    ],
    initiativesCatalog: [
      {
        id: 'init-strangler-core',
        name: 'Strangler Fig Core Modernization',
        category: 'MODERNIZATION',
        description: 'Incrementally carve out transactions from the COBOL mainframe to cloud-native microservices.',
        capExCost: 350,
        opExDelta: -45,
        tdiDelta: -24,
        velocityDelta: 16,
        resilienceDelta: 20,
        complianceDelta: 12,
        trustDelta: { 'sh-cto-elena': 16, 'sh-vp-priya': 8, 'sh-cfo-marcus': -6 },
        affectedNodeIds: ['node-legacy-core', 'node-mod-services'],
        durationRounds: 1,
        riskLevel: 'MEDIUM',
      },
      {
        id: 'init-kafka-ledger',
        name: 'Kafka Distributed Financial Ledger',
        category: 'MODERNIZATION',
        description: 'Migrate synchronous batch updates to event-driven streaming architecture.',
        capExCost: 280,
        opExDelta: -25,
        tdiDelta: -18,
        velocityDelta: 14,
        resilienceDelta: 22,
        complianceDelta: 8,
        trustDelta: { 'sh-cto-elena': 14, 'sh-cfo-marcus': -5 },
        affectedNodeIds: ['node-db-mainframe', 'node-kafka-bus'],
        durationRounds: 1,
        riskLevel: 'LOW',
      },
      {
        id: 'init-cloud-mesh',
        name: 'Multi-Region Cloud Mesh Deployment',
        category: 'CLOUD_INFRA',
        description: 'Decommission legacy on-prem datacenter racks and migrate to automated multi-zone Kubernetes.',
        capExCost: 400,
        opExDelta: -55,
        tdiDelta: -16,
        velocityDelta: 15,
        resilienceDelta: 26,
        complianceDelta: 14,
        trustDelta: { 'sh-cfo-marcus': 12, 'sh-cto-elena': 15 },
        affectedNodeIds: ['node-infra-onprem', 'node-infra-cloud'],
        durationRounds: 1,
        riskLevel: 'HIGH',
      },
      {
        id: 'init-shadow-feature-sprint',
        name: 'Bypass Architecture Feature Blitz',
        category: 'FEATURE_EXPEDITE',
        description: 'Hardcode direct database queries and bypass architectural review to push marketing features.',
        capExCost: 150,
        opExDelta: 50,
        tdiDelta: 22,
        velocityDelta: 28,
        resilienceDelta: -18,
        complianceDelta: -22,
        trustDelta: { 'sh-vp-priya': 24, 'sh-cto-elena': -25, 'sh-cso-arthur': -20 },
        affectedNodeIds: ['node-biz-app', 'node-legacy-core'],
        durationRounds: 1,
        riskLevel: 'EXTREME',
      },
      {
        id: 'init-zero-trust-sec',
        name: 'Zero-Trust mTLS & Automated Audit Fabric',
        category: 'SECURITY_COMPLIANCE',
        description: 'Deploy hardware security modules, automated token rotation, and immutable audit logs.',
        capExCost: 220,
        opExDelta: -10,
        tdiDelta: -12,
        velocityDelta: -5,
        resilienceDelta: 18,
        complianceDelta: 32,
        trustDelta: { 'sh-cso-arthur': 28, 'sh-cto-elena': 10, 'sh-vp-priya': -6 },
        affectedNodeIds: ['node-api-gw', 'node-db-mainframe'],
        durationRounds: 1,
        riskLevel: 'LOW',
      },
      {
        id: 'init-ai-ops-copilot',
        name: 'AI Operations & Synthetic Telemetry Sharding',
        category: 'AI_AUTOMATION',
        description: 'Autonomous AI probes detecting database deadlocks and routing traffic dynamically.',
        capExCost: 240,
        opExDelta: -30,
        tdiDelta: -14,
        velocityDelta: 16,
        resilienceDelta: 20,
        complianceDelta: 6,
        trustDelta: { 'sh-cto-elena': 12, 'sh-cfo-marcus': 10, 'sh-vp-priya': 10 },
        affectedNodeIds: ['node-api-gw', 'node-mod-services'],
        durationRounds: 1,
        riskLevel: 'MEDIUM',
      },
    ],
    tags: ['FinTech', 'Core Banking', 'Mainframe Migration', 'PCI-DSS', 'Executive Strategy'],
    author: 'GemSim Enterprise Curators',
    isDefault: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'scen-healthtech-healthnova',
    title: 'HealthNova: Clinical EHR & Telehealth Overhaul',
    industry: 'Healthcare & Life Sciences',
    domain: 'IT',
    language: 'en',
    difficulty: 'EXECUTIVE',
    description: 'Lead a 15-hospital regional network out of a legacy EHR monolith lock-in, scale telehealth that collapses at peak hours, and pass HIPAA scrutiny while keeping clinical uptime and the cash runway intact.',
    businessContext: 'HealthNova runs 15 regional hospitals on a legacy EHR monolith carrying a 68% Technical Debt Index. Peak-hour telehealth consultations suffer critical video latency, clinicians are burning out on slow charting, and every integration (mobile app, pharmacies, analytics) goes through brittle point-to-point HL7 feeds.',
    baselineMetrics: {
      tco: 2800,
      budgetRemaining: 1800,
      opEx: 630,
      capExSpent: 500,
      technicalDebtIndex: 68,
      deliveryVelocity: 42,
      stakeholderTrust: 55,
      resilienceIndex: 52,
      complianceScore: 68,
      modernizedNodesCount: 1,
    },
    winLossConditions: {
      maxTechnicalDebtIndex: 40,
      minStakeholderTrustAvg: 62,
      minDeliveryVelocity: 60,
      minResilienceIndex: 78,
      maxTCOBudget: 5200,
      targetCapabilitiesModernized: 4,
    },
    totalRounds: 4,
    maxInitiativesPerRound: 2,
    topology: {
      nodes: [
        {
          id: 'hn-ehr-core',
          name: 'Legacy EHR Core',
          layer: 'DATA',
          archetype: 'DATABASE',
          description: 'Monolithic EHR database: patient charts, medication orders and lab results for 15 hospitals.',
          health: 42,
          technicalDebt: 82,
          criticalPath: true,
          costPerRound: 190,
          position: { x: 0, y: -2, z: 0 },
          status: 'CRITICAL',
          dependencies: ['hn-dr-vault'],
          telemetry: { latencyMs: 780, throughputRps: 520, errorRatePercent: 3.8, failureRisk: 84 },
        },
        {
          id: 'hn-ingestion',
          name: 'Clinical Data Ingestion',
          layer: 'APPLICATION',
          archetype: 'SLAB',
          description: 'HL7 v2 / FHIR pipeline normalizing feeds from labs, devices and partner systems into the EHR.',
          health: 50,
          technicalDebt: 70,
          criticalPath: true,
          costPerRound: 85,
          position: { x: -3, y: 1, z: 0 },
          status: 'DEGRADED',
          dependencies: ['hn-ehr-core'],
          telemetry: { latencyMs: 420, throughputRps: 900, errorRatePercent: 2.4, failureRisk: 66 },
        },
        {
          id: 'hn-telehealth',
          name: 'Telehealth Video Gateway',
          layer: 'APPLICATION',
          archetype: 'TOWER',
          description: 'WebRTC media gateway for video consultations; saturates during peak clinic hours.',
          health: 54,
          technicalDebt: 62,
          criticalPath: true,
          costPerRound: 80,
          position: { x: 3, y: 2, z: 0 },
          status: 'DEGRADED',
          dependencies: ['hn-identity', 'hn-ehr-core'],
          telemetry: { latencyMs: 640, throughputRps: 1400, errorRatePercent: 3.1, failureRisk: 62 },
        },
        {
          id: 'hn-mobile',
          name: 'Patient Mobile Portal',
          layer: 'BUSINESS',
          archetype: 'SLAB',
          description: 'Patient app and portal: appointments, results, prescriptions refills and telehealth entry point.',
          health: 74,
          technicalDebt: 36,
          criticalPath: false,
          costPerRound: 50,
          position: { x: -4, y: 5, z: 0 },
          status: 'HEALTHY',
          dependencies: ['hn-identity', 'hn-ingestion'],
          telemetry: { latencyMs: 85, throughputRps: 2200, errorRatePercent: 0.4, failureRisk: 22 },
        },
        {
          id: 'hn-analytics',
          name: 'Analytics & Reporting Engine',
          layer: 'DATA',
          archetype: 'DATABASE',
          description: 'Clinical warehouse fed by nightly EHR extracts: quality indicators, capacity planning, research.',
          health: 56,
          technicalDebt: 64,
          criticalPath: false,
          costPerRound: 70,
          position: { x: 4, y: -3, z: 0 },
          status: 'DEGRADED',
          dependencies: ['hn-ehr-core'],
          telemetry: { latencyMs: 360, throughputRps: 600, errorRatePercent: 1.6, failureRisk: 48 },
        },
        {
          id: 'hn-identity',
          name: 'Identity & Zero-Trust Auth',
          layer: 'INFRASTRUCTURE',
          archetype: 'TOWER',
          description: 'Clinician and patient identity, MFA and access policies guarding PHI.',
          health: 58,
          technicalDebt: 58,
          criticalPath: true,
          costPerRound: 55,
          position: { x: 0, y: 4, z: 0 },
          status: 'DEGRADED',
          dependencies: [],
          telemetry: { latencyMs: 140, throughputRps: 3000, errorRatePercent: 0.9, failureRisk: 46 },
        },
        {
          id: 'hn-pharmacy',
          name: 'Third-Party Pharmacy Integration',
          layer: 'APPLICATION',
          archetype: 'SLAB',
          description: 'Partner gateway exchanging e-prescriptions and dispensing status with external pharmacies.',
          health: 60,
          technicalDebt: 52,
          criticalPath: false,
          costPerRound: 40,
          position: { x: -6, y: 0, z: 0 },
          status: 'DEGRADED',
          dependencies: ['hn-ingestion'],
          telemetry: { latencyMs: 240, throughputRps: 500, errorRatePercent: 1.2, failureRisk: 34 },
        },
        {
          id: 'hn-dr-vault',
          name: 'Disaster Recovery Vault',
          layer: 'DATA',
          archetype: 'DATABASE',
          description: 'Immutable, encrypted backup vault replicated off-site; the last line of defense against ransomware.',
          health: 86,
          technicalDebt: 18,
          criticalPath: false,
          costPerRound: 45,
          position: { x: 0, y: -6, z: 0 },
          status: 'MODERNIZED',
          dependencies: [],
          telemetry: { latencyMs: 60, throughputRps: 800, errorRatePercent: 0.05, failureRisk: 8 },
        },
      ],
      edges: [
        { id: 'he1', fromId: 'hn-mobile', toId: 'hn-identity', protocol: 'OAuth2 / OIDC', bandwidthMbps: 1000, status: 'NORMAL', latencyMs: 30 },
        { id: 'he2', fromId: 'hn-mobile', toId: 'hn-ingestion', protocol: 'FHIR REST', bandwidthMbps: 500, status: 'NORMAL', latencyMs: 90 },
        { id: 'he3', fromId: 'hn-telehealth', toId: 'hn-identity', protocol: 'mTLS', bandwidthMbps: 1000, status: 'NORMAL', latencyMs: 25 },
        { id: 'he4', fromId: 'hn-telehealth', toId: 'hn-ehr-core', protocol: 'HL7 v2 Query', bandwidthMbps: 300, status: 'BOTTLENECK', latencyMs: 420 },
        { id: 'he5', fromId: 'hn-ingestion', toId: 'hn-ehr-core', protocol: 'HL7 v2 / MLLP', bandwidthMbps: 400, status: 'BOTTLENECK', latencyMs: 380 },
        { id: 'he6', fromId: 'hn-pharmacy', toId: 'hn-ingestion', protocol: 'NCPDP SCRIPT', bandwidthMbps: 200, status: 'NORMAL', latencyMs: 160 },
        { id: 'he7', fromId: 'hn-ehr-core', toId: 'hn-analytics', protocol: 'Nightly ETL', bandwidthMbps: 600, status: 'BOTTLENECK', latencyMs: 900 },
        { id: 'he8', fromId: 'hn-ehr-core', toId: 'hn-dr-vault', protocol: 'Encrypted Replication', bandwidthMbps: 1000, status: 'OPTIMIZED', latencyMs: 40 },
      ],
    },
    stakeholders: [
      {
        id: 'sh-cmo-sarah',
        name: 'Dr. Sarah Lin',
        title: 'Chief Medical Officer',
        role: 'Clinical Care & Patient Safety',
        avatar: '🩺',
        personality: 'Patient-centric, fiercely protective of doctor workflow and clinical uptime.',
        bias: 'Zero patience for IT disruptions during surgical or inpatient hours.',
        hiddenAgenda: 'Championing physician satisfaction to reduce clinician burnout before contract renewals.',
        negotiationTolerance: 45,
        baseTrust: 60,
        decisionWeights: { financialAcumen: 0.1, deliverySpeed: 0.35, architecturalRigor: 0.25, regulatoryCompliance: 0.3 },
        sampleDialogue: {
          greeting: 'A system crash in the emergency room is not a ticket. It is a patient risk.',
          resistance: 'Do not touch the clinical charting interface unless you can guarantee zero downtime.',
          concession: 'If telehealth stops freezing at peak hours and saves our physicians 20 minutes per shift, you have my support.',
        },
      },
      {
        id: 'sh-cio-david',
        name: 'David Thornton',
        title: 'Chief Information Officer',
        role: 'Healthcare Enterprise Architecture',
        avatar: '🏥',
        personality: 'Careful, experienced, risk-averse enterprise strategist.',
        bias: 'Balances legacy mainframe stability with cloud agility; distrusts big-bang rewrites.',
        hiddenAgenda: 'Navigating an impending Joint Commission and HIPAA federal audit without findings.',
        negotiationTolerance: 55,
        baseTrust: 55,
        decisionWeights: { financialAcumen: 0.2, deliverySpeed: 0.15, architecturalRigor: 0.4, regulatoryCompliance: 0.25 },
        sampleDialogue: {
          greeting: 'We manage life-critical infrastructure. Stability precedes innovation.',
          resistance: 'Ripping out the EHR core in one go is how hospitals end up on the evening news.',
          concession: 'Deliver a validated FHIR abstraction first, and I will back an incremental strangler migration.',
        },
      },
      {
        id: 'sh-cfo-victoria',
        name: 'Victoria Sterling',
        title: 'Chief Financial Officer',
        role: 'Budget Runway & OpEx Containment',
        avatar: '💼',
        personality: 'Precise, numbers-first, allergic to open-ended programs.',
        bias: 'Every dollar of CapEx must show an OpEx reduction within four quarters.',
        hiddenAgenda: 'Protecting the bond rating ahead of a hospital expansion financing round.',
        negotiationTolerance: 40,
        baseTrust: 50,
        decisionWeights: { financialAcumen: 0.6, deliverySpeed: 0.15, architecturalRigor: 0.1, regulatoryCompliance: 0.15 },
        sampleDialogue: {
          greeting: 'Show me the runway. How many quarters of cash does this plan leave us?',
          resistance: 'I will not fund a migration with no gate and no OpEx target attached.',
          concession: 'Phase it with a measurable OpEx reduction gate each quarter and I will release the tranches.',
        },
      },
    ],
    roundEvents: [
      {
        roundNumber: 1,
        title: 'Q1: Telehealth Collapses Under Regional Flu Wave',
        description: 'Peak-hour video consultations triple; the WebRTC gateway drops calls and clinicians fall back to phone triage.',
        type: 'DISRUPTION',
        severity: 'HIGH',
        immediateImpact: { budgetFine: 80, tdiSurge: 5, velocityPenalty: -10 },
        choices: [
          { id: 'he-c1', text: 'Spin up cloud WebRTC edge relays (fast relief)', capExImpact: 120, tdiImpact: -4, velocityImpact: 8, trustImpact: { 'sh-cmo-sarah': 14, 'sh-cfo-victoria': -4 }, nodeHealthImpacts: { 'hn-telehealth': 15 } },
          { id: 'he-c2', text: 'Queue patient video calls (frustrates clinicians)', capExImpact: 20, tdiImpact: 2, velocityImpact: -12, trustImpact: { 'sh-cmo-sarah': -18, 'sh-cfo-victoria': 6 } },
        ],
      },
      {
        roundNumber: 2,
        title: 'Q2: Surprise HIPAA Office for Civil Rights Audit',
        description: 'Federal auditors request PHI access logs and encryption evidence across hospital datacenters.',
        type: 'AUDIT',
        severity: 'HIGH',
        immediateImpact: { budgetFine: 150, tdiSurge: 0, velocityPenalty: -12 },
        choices: [
          { id: 'he-c3', text: 'Run an emergency access-logging and encryption sprint', capExImpact: 160, tdiImpact: -6, velocityImpact: -4, trustImpact: { 'sh-cio-david': 16, 'sh-cfo-victoria': -6 } },
          { id: 'he-c4', text: 'Accept a consent decree and pay the settlement', capExImpact: 240, tdiImpact: 4, velocityImpact: 0, trustImpact: { 'sh-cio-david': -15, 'sh-cfo-victoria': -10 } },
        ],
      },
      {
        roundNumber: 3,
        title: 'Q3: Ransomware Lateral Movement Toward the EHR',
        description: 'A phishing foothold moves laterally toward the EHR core; identity services show compromised credentials.',
        type: 'CRISIS',
        severity: 'BLACK_SWAN',
        immediateImpact: { budgetFine: 220, tdiSurge: 8, velocityPenalty: -18, downedNodeIds: ['hn-ehr-core', 'hn-identity'] },
        choices: [
          { id: 'he-c5', text: 'Isolate segments and restore from the immutable DR vault', capExImpact: 180, tdiImpact: -8, velocityImpact: 4, trustImpact: { 'sh-cmo-sarah': 8, 'sh-cio-david': 15 }, nodeHealthImpacts: { 'hn-ehr-core': 10 } },
          { id: 'he-c6', text: 'Pay a ransom negotiator (high liability)', capExImpact: 350, tdiImpact: 10, velocityImpact: -10, trustImpact: { 'sh-cio-david': -25, 'sh-cfo-victoria': -15 } },
        ],
      },
      {
        roundNumber: 4,
        title: 'Q4: Regional Health Board Review',
        description: 'Final review of clinical uptime, patient satisfaction, compliance posture and operating margins.',
        type: 'MARKET_SHIFT',
        severity: 'MEDIUM',
        immediateImpact: { budgetFine: 0, tdiSurge: 0, velocityPenalty: 0 },
        choices: [
          { id: 'he-c7', text: 'Present the unified clinical platform results', capExImpact: 80, tdiImpact: -4, velocityImpact: 6, trustImpact: { 'sh-cmo-sarah': 10, 'sh-cio-david': 10 } },
          { id: 'he-c8', text: 'Freeze modernization to rebuild cash reserves', capExImpact: -100, tdiImpact: 8, velocityImpact: -10, trustImpact: { 'sh-cmo-sarah': -12, 'sh-cfo-victoria': 14 } },
        ],
      },
    ],
    initiativesCatalog: [
      {
        id: 'h-init-strangler',
        name: 'Strangler Fig EHR Migration',
        category: 'MODERNIZATION',
        description: 'Incrementally carve clinical capabilities (orders, results) out of the EHR core into cloud services behind the ingestion layer. Two quarters to deliver.',
        capExCost: 380,
        opExDelta: -40,
        tdiDelta: -22,
        velocityDelta: 14,
        resilienceDelta: 18,
        complianceDelta: 8,
        trustDelta: { 'sh-cio-david': 14, 'sh-cmo-sarah': -4, 'sh-cfo-victoria': 6 },
        affectedNodeIds: ['hn-ehr-core', 'hn-ingestion'],
        durationRounds: 2,
        riskLevel: 'HIGH',
      },
      {
        id: 'h-init-fhir',
        name: 'FHIR API Abstraction',
        category: 'MODERNIZATION',
        description: 'Standard FHIR API layer insulating the EHR from the mobile portal and pharmacy partners.',
        capExCost: 260,
        opExDelta: -20,
        tdiDelta: -16,
        velocityDelta: 16,
        resilienceDelta: 12,
        complianceDelta: 16,
        trustDelta: { 'sh-cio-david': 12, 'sh-cmo-sarah': 8 },
        affectedNodeIds: ['hn-ingestion', 'hn-mobile', 'hn-pharmacy'],
        durationRounds: 1,
        riskLevel: 'LOW',
      },
      {
        id: 'h-init-kafka',
        name: 'Kafka Clinical Event Streaming',
        category: 'CLOUD_INFRA',
        description: 'Real-time clinical event backbone feeding telehealth context and analytics instead of nightly batch extracts.',
        capExCost: 300,
        opExDelta: -25,
        tdiDelta: -14,
        velocityDelta: 14,
        resilienceDelta: 18,
        complianceDelta: 4,
        trustDelta: { 'sh-cmo-sarah': 12, 'sh-cfo-victoria': -4 },
        affectedNodeIds: ['hn-telehealth', 'hn-analytics'],
        durationRounds: 1,
        riskLevel: 'MEDIUM',
      },
      {
        id: 'h-init-zerotrust',
        name: 'Zero-Trust Compliance Program',
        category: 'SECURITY_COMPLIANCE',
        description: 'Clinician MFA, least-privilege PHI access, audit telemetry and DR vault hardening for HIPAA readiness.',
        capExCost: 220,
        opExDelta: -5,
        tdiDelta: -10,
        velocityDelta: -4,
        resilienceDelta: 22,
        complianceDelta: 30,
        trustDelta: { 'sh-cio-david': 16, 'sh-cfo-victoria': -4 },
        affectedNodeIds: ['hn-identity', 'hn-dr-vault'],
        durationRounds: 1,
        riskLevel: 'LOW',
      },
      {
        id: 'h-init-bypass',
        name: 'Emergency Direct EHR Database Query Scripts',
        category: 'FEATURE_EXPEDITE',
        description: 'Hardcode direct database queries to expedite clinical research reports without architectural gating.',
        capExCost: 90,
        opExDelta: 40,
        tdiDelta: 20,
        velocityDelta: 22,
        resilienceDelta: -16,
        complianceDelta: -28,
        trustDelta: { 'sh-cmo-sarah': 14, 'sh-cio-david': -24, 'sh-cfo-victoria': 4 },
        affectedNodeIds: ['hn-ehr-core', 'hn-analytics'],
        durationRounds: 1,
        riskLevel: 'EXTREME',
      },
    ],
    tags: ['Healthcare', 'HIPAA', 'EHR Monolith', 'Telehealth', 'Clinical Resilience'],
    author: 'GemSim Healthcare Working Group',
    isDefault: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'scen-offshore-mirage',
    title: 'Mirage Offshore : Arbitrage Coûts, Souveraineté et Dette Technique',
    industry: 'Grande Entreprise de Services / Assurance et Fintech',
    domain: 'SOURCING',
    language: 'fr',
    currency: 'EUR',
    difficulty: 'EXECUTIVE',
    description: 'Arbitrage stratégique entre réduction des coûts via l\'externalisation et préservation du patrimoine architectural, de la souveraineté des données et des compétences internes.',
    businessContext: 'La direction générale impose une réduction de 35% de l\'OpEx IT via un contrat cadre avec une ESN offshore. Les équipes internes tirent la sonnette d\'alarme sur l\'hémorragie de compétences, la duplication de code et la perte de maîtrise du socle applicatif souverain.',
    baselineMetrics: {
      tco: 3200,
      budgetRemaining: 1800,
      opEx: 680,
      capExSpent: 450,
      technicalDebtIndex: 68,
      deliveryVelocity: 46,
      stakeholderTrust: 55,
      resilienceIndex: 52,
      complianceScore: 68,
      modernizedNodesCount: 2,
    },
    winLossConditions: {
      maxTechnicalDebtIndex: 42,
      minStakeholderTrustAvg: 65,
      minDeliveryVelocity: 62,
      minResilienceIndex: 78,
      maxTCOBudget: 5800,
      targetCapabilitiesModernized: 4,
    },
    totalRounds: 4,
    topology: {
      nodes: [
        {
          id: 'node-offshore-center',
          name: 'Offshore Delivery Center',
          layer: 'APPLICATION',
          description: 'Pôle de développement externalisé en régie/forfait avec forte rotation d\'ingénieurs et décalage horaire.',
          health: 48,
          technicalDebt: 72,
          criticalPath: true,
          costPerRound: 75,
          position: { x: -8.5, y: 0, z: 2.5 },
          status: 'CRITICAL',
          dependencies: ['node-dev-pipeline'],
          telemetry: { latencyMs: 290, throughputRps: 720, errorRatePercent: 3.6, failureRisk: 74 },
        },
        {
          id: 'node-reg-reporting',
          name: 'Regulatory Reporting',
          layer: 'DATA',
          description: 'Moteur de conformité réglementaire (DORA, RGPD, ACPR) alimenté par les données de transaction.',
          health: 72,
          technicalDebt: 34,
          criticalPath: false,
          costPerRound: 45,
          position: { x: -7.5, y: 0, z: -2.5 },
          status: 'HEALTHY',
          dependencies: ['node-core-logic'],
          telemetry: { latencyMs: 80, throughputRps: 1100, errorRatePercent: 0.1, failureRisk: 22 },
        },
        {
          id: 'node-dev-pipeline',
          name: 'Dev Pipeline',
          layer: 'APPLICATION',
          description: 'Pipeline CI/CD transfrontalier avec validation automatisée des pull requests et contrôle des dépendances.',
          health: 58,
          technicalDebt: 55,
          criticalPath: true,
          costPerRound: 50,
          position: { x: -4.0, y: 0, z: 0.5 },
          status: 'DEGRADED',
          dependencies: ['node-arch-guardrail'],
          telemetry: { latencyMs: 45, throughputRps: 3400, errorRatePercent: 0.8, failureRisk: 40 },
        },
        {
          id: 'node-arch-guardrail',
          name: 'Architecture Guardrail',
          layer: 'APPLICATION',
          description: 'Passerelle de gouvernance mTLS, contrats d\'interface stricts et revue d\'architecture automatique.',
          health: 82,
          technicalDebt: 22,
          criticalPath: true,
          costPerRound: 40,
          position: { x: 0.0, y: 0, z: 0.0 },
          status: 'HEALTHY',
          dependencies: ['node-onshore-eng', 'node-core-logic'],
          telemetry: { latencyMs: 18, throughputRps: 4600, errorRatePercent: 0.02, failureRisk: 10 },
        },
        {
          id: 'node-knowledge-base',
          name: 'Knowledge Base',
          layer: 'DATA',
          description: 'Référentiel de documentation d\'architecture, cartographie des flux et standards de développement.',
          health: 55,
          technicalDebt: 60,
          criticalPath: false,
          costPerRound: 35,
          position: { x: 2.8, y: 0, z: 2.6 },
          status: 'DEGRADED',
          dependencies: ['node-onshore-eng'],
          telemetry: { latencyMs: 95, throughputRps: 850, errorRatePercent: 0.4, failureRisk: 36 },
        },
        {
          id: 'node-onshore-eng',
          name: 'Onshore Engineering',
          layer: 'BUSINESS',
          description: 'Équipes d\'ingénierie et d\'architecture internes garantes du savoir-faire métier et de l\'innovation.',
          health: 72,
          technicalDebt: 38,
          criticalPath: true,
          costPerRound: 90,
          position: { x: 5.6, y: 0, z: -1.8 },
          status: 'HEALTHY',
          dependencies: ['node-core-logic'],
          telemetry: { latencyMs: 25, throughputRps: 1500, errorRatePercent: 0.05, failureRisk: 18 },
        },
        {
          id: 'node-core-logic',
          name: 'Core Business Logic',
          layer: 'APPLICATION',
          description: 'Socle applicatif souverain regroupant les règles métier de souscription, de tarification et de sinistres.',
          health: 50,
          technicalDebt: 65,
          criticalPath: true,
          costPerRound: 120,
          position: { x: 8.8, y: 0, z: 0.5 },
          status: 'DEGRADED',
          dependencies: ['node-data-vault'],
          telemetry: { latencyMs: 340, throughputRps: 920, errorRatePercent: 1.8, failureRisk: 66 },
        },
        {
          id: 'node-data-vault',
          name: 'Sensitive Data Vault',
          layer: 'DATA',
          description: 'Coffre-fort de données souveraines sous confinement juridique strict (données clients et bancaires).',
          health: 78,
          technicalDebt: 28,
          criticalPath: true,
          costPerRound: 85,
          position: { x: 11.0, y: 0, z: -2.8 },
          status: 'HEALTHY',
          dependencies: [],
          telemetry: { latencyMs: 70, throughputRps: 2100, errorRatePercent: 0.05, failureRisk: 16 },
        },
      ],
      edges: [
        { id: 'mo-e1', fromId: 'node-dev-pipeline', toId: 'node-offshore-center', protocol: 'mTLS', bandwidthMbps: 1000, latencyMs: 250, status: 'BOTTLENECK' },
        { id: 'mo-e2', fromId: 'node-dev-pipeline', toId: 'node-arch-guardrail', protocol: 'HTTPS', bandwidthMbps: 2500, latencyMs: 40, status: 'OPTIMIZED' },
        { id: 'mo-e3', fromId: 'node-arch-guardrail', toId: 'node-onshore-eng', protocol: 'gRPC', bandwidthMbps: 5000, latencyMs: 15, status: 'OPTIMIZED' },
        { id: 'mo-e4', fromId: 'node-arch-guardrail', toId: 'node-core-logic', protocol: 'REST', bandwidthMbps: 1500, latencyMs: 120, status: 'BOTTLENECK' },
        { id: 'mo-e5', fromId: 'node-onshore-eng', toId: 'node-knowledge-base', protocol: 'HTTPS', bandwidthMbps: 1000, latencyMs: 30, status: 'NORMAL' },
        { id: 'mo-e6', fromId: 'node-core-logic', toId: 'node-data-vault', protocol: 'TCP/TLS', bandwidthMbps: 4000, latencyMs: 20, status: 'OPTIMIZED' },
        { id: 'mo-e7', fromId: 'node-core-logic', toId: 'node-reg-reporting', protocol: 'Kafka', bandwidthMbps: 2000, latencyMs: 60, status: 'NORMAL' },
      ],
    },
    stakeholders: [
      {
        id: 'sh-cfo-julien',
        name: 'Julien Marchand',
        title: 'Directeur Financier (CFO)',
        role: 'Optimisation Budgétaire & Rentabilité',
        avatar: '💼',
        personality: 'Focalisé sur la réduction drastique des coûts et le respect de la trajectoire budgétaire.',
        bias: 'Considère le développement offshore comme le levier prioritaire de compression des dépenses.',
        hiddenAgenda: 'Obtenir une prime sur objectif en atteignant 35% d\'économies sur la masse salariale IT.',
        negotiationTolerance: 45,
        baseTrust: 50,
        decisionWeights: { financialAcumen: 0.7, deliverySpeed: 0.15, architecturalRigor: 0.05, regulatoryCompliance: 0.1 },
        sampleDialogue: {
          greeting: 'Notre ratio d\'exploitation est sous pression. L\'arbitrage offshore n\'est pas négociable.',
          resistance: 'Tout rapatriement de charge onshore doit être autofinancé par des gains de productivité immédiats.',
          concession: 'Si vous prouvez que les revues de code réduisent les pénalités contractuelles, je débloque un budget d\'outillage.',
        },
      },
      {
        id: 'sh-arch-claire',
        name: 'Claire Vasseur',
        title: 'Directrice de l\'Architecture d\'Entreprise',
        role: 'Gouvernance & Souveraineté Technologique',
        avatar: '🛡️',
        personality: 'Rigoureuse, intransigeante sur les standards et la pérennité du patrimoine logiciel.',
        bias: 'Opposée à l\'externalisation massive sans sas de contrôle d\'architecture et documentation stricte.',
        hiddenAgenda: 'Sanctuariser le coeur métier et réinternaliser les compétences d\'ingénierie stratégiques.',
        negotiationTolerance: 65,
        baseTrust: 65,
        decisionWeights: { financialAcumen: 0.1, deliverySpeed: 0.15, architecturalRigor: 0.6, regulatoryCompliance: 0.15 },
        sampleDialogue: {
          greeting: 'L\'offshore sans garde-fous produit du code jetable et une dette technique ingérable.',
          resistance: 'Accorder des accès directs à la base de données au prestataire viole notre politique de souveraineté.',
          concession: 'Mettons en place une passerelle API stricte et des revues paritaires avant toute mise en production.',
        },
      },
      {
        id: 'sh-esn-rajesh',
        name: 'Rajesh Sharma',
        title: 'Directeur de Compte ESN Offshore',
        role: 'Engagement de Service & Delivery Tiers',
        avatar: '🌐',
        personality: 'Diplomate, orienté volume et respect des jalons contractuels.',
        bias: 'Privilégie le respect des délais et la rentabilité du forfait au détriment de l\'adhérence fine aux standards.',
        hiddenAgenda: 'Maximiser le volume d\'heures facturables et convertir les anomalies en avenants payants.',
        negotiationTolerance: 50,
        baseTrust: 55,
        decisionWeights: { financialAcumen: 0.25, deliverySpeed: 0.55, architecturalRigor: 0.1, regulatoryCompliance: 0.1 },
        sampleDialogue: {
          greeting: 'Mes équipes sont mobilisées 24/7 pour livrer le sprint conformément au cahier des charges.',
          resistance: 'Si les spécifications changent ou que les revues bloquent les releases, nous devrons émettre un avenant.',
          concession: 'Nous acceptons d\'intégrer un lead architecte dédié à vos quality gates sans surcoût.',
        },
      },
    ],
    roundEvents: [
      {
        roundNumber: 1,
        title: 'Q1 : Choc de Communication & Friction Culturelle',
        description: 'La première release majeure développée offshore présente un taux de non-conformité de 42% aux standards d\'architecture. Les équipes internes refusent de déployer.',
        type: 'CRISIS',
        severity: 'HIGH',
        immediateImpact: { budgetFine: 80, tdiSurge: 10, velocityPenalty: 12 },
        choices: [
          {
            id: 'mo-q1-c1',
            text: 'Mettre en place des Quality Gates automatisées et un sas de validation paritaire',
            capExImpact: 75,
            tdiImpact: -8,
            velocityImpact: -5,
            trustImpact: { 'sh-arch-claire': 12, 'sh-cfo-julien': -4, 'sh-esn-rajesh': 6 },
            nodeHealthImpacts: { 'node-arch-guardrail': 25, 'node-dev-pipeline': 20 },
          },
          {
            id: 'mo-q1-c2',
            text: 'Forcer la mise en production pour respecter l\'échéance commerciale du CFO',
            capExImpact: 20,
            tdiImpact: 14,
            velocityImpact: 10,
            trustImpact: { 'sh-cfo-julien': 10, 'sh-arch-claire': -18, 'sh-esn-rajesh': 8 },
            nodeHealthImpacts: { 'node-core-logic': -20 },
          },
        ],
      },
      {
        roundNumber: 2,
        title: 'Q2 : Fuite de Données de Test & Audit Réglementaire',
        description: 'Des données clients de production ont été copiées dans l\'environnement de staging distant sans anonymisation préalable.',
        type: 'AUDIT',
        severity: 'BLACK_SWAN',
        immediateImpact: { budgetFine: 160, tdiSurge: 8, velocityPenalty: 15 },
        choices: [
          {
            id: 'mo-q2-c1',
            text: 'Déployer une plateforme de génération de données de synthèse et durcir le sas API',
            capExImpact: 120,
            tdiImpact: -6,
            velocityImpact: -8,
            trustImpact: { 'sh-arch-claire': 14, 'sh-cfo-julien': -8 },
            nodeHealthImpacts: { 'node-data-vault': 30 },
          },
          {
            id: 'mo-q2-c2',
            text: 'Signer un avenant de non-divulgation renforcé avec l\'ESN sans refonte technique',
            capExImpact: 40,
            tdiImpact: 8,
            velocityImpact: 0,
            trustImpact: { 'sh-cfo-julien': 6, 'sh-arch-claire': -14 },
            nodeHealthImpacts: {},
          },
        ],
      },
      {
        roundNumber: 3,
        title: 'Q3 : Turnover Critique au Centre Distant',
        description: '70% de l\'équipe offshore quitte le projet en 2 mois, entraînant une perte sèche de la connaissance tacite du code.',
        type: 'DISRUPTION',
        severity: 'HIGH',
        immediateImpact: { budgetFine: 50, tdiSurge: 12, velocityPenalty: 20 },
        choices: [
          {
            id: 'mo-q3-c1',
            text: 'Financer des sessions de pair-programming onshore/offshore et sanctuariser la documentation',
            capExImpact: 90,
            tdiImpact: -10,
            velocityImpact: -6,
            trustImpact: { 'sh-arch-claire': 10, 'sh-esn-rajesh': 12 },
            nodeHealthImpacts: { 'node-knowledge-base': 35 },
          },
          {
            id: 'mo-q3-c2',
            text: 'Exiger le remplacement immédiat des effectifs sous astreinte contractuelle',
            capExImpact: 10,
            tdiImpact: 12,
            velocityImpact: -15,
            trustImpact: { 'sh-esn-rajesh': -16, 'sh-cfo-julien': 4 },
            nodeHealthImpacts: { 'node-offshore-center': -25 },
          },
        ],
      },
      {
        roundNumber: 4,
        title: 'Q4 : Arbitrage de Renouvellement Contractuel',
        description: 'Le contrat triennal de sous-traitance arrive à échéance. La direction générale attend la recommandation stratégique finale.',
        type: 'MARKET_SHIFT',
        severity: 'MEDIUM',
        immediateImpact: { budgetFine: 0, tdiSurge: 0, velocityPenalty: 0 },
        choices: [
          {
            id: 'mo-q4-c1',
            text: 'Modèle Hybride Souverain : Réinternaliser le socle stratégique et confier les commodités à l\'ESN sous SLA stricts',
            capExImpact: 150,
            tdiImpact: -18,
            velocityImpact: 14,
            trustImpact: { 'sh-arch-claire': 18, 'sh-cfo-julien': 10, 'sh-esn-rajesh': 8 },
            nodeHealthImpacts: { 'node-onshore-eng': 30, 'node-core-logic': 25 },
          },
          {
            id: 'mo-q4-c2',
            text: '100% Offshore : Transférer l\'intégralité des périmètres pour maximiser l\'économie faciale',
            capExImpact: 30,
            tdiImpact: 22,
            velocityImpact: -10,
            trustImpact: { 'sh-cfo-julien': 16, 'sh-arch-claire': -25, 'sh-esn-rajesh': 15 },
            nodeHealthImpacts: { 'node-core-logic': -35 },
          },
        ],
      },
    ],
    initiativesCatalog: [
      {
        id: 'mo-init-guardrail',
        name: 'Passerelle de Contrôle & Quality Gates Automatisées',
        category: 'GOVERNANCE_STRICT',
        description: 'Déploiement de SonarQube, de contrats d\'API stricts (OpenAPI/mTLS) et de revues obligatoires par les architectes onshore.',
        capExCost: 220,
        opExDelta: -30,
        tdiDelta: -16,
        velocityDelta: -4,
        resilienceDelta: 20,
        complianceDelta: 18,
        trustDelta: { 'sh-arch-claire': 16, 'sh-cfo-julien': -4 },
        affectedNodeIds: ['node-arch-guardrail', 'node-dev-pipeline'],
        durationRounds: 1,
        riskLevel: 'LOW',
      },
      {
        id: 'mo-init-kb',
        name: 'Plateforme de Documentation & Cartographie Vivante',
        category: 'DEBT_REDUCTION',
        description: 'Capitalisation de la connaissance métier et documentation de l\'architecture applicative pour contrer le turnover.',
        capExCost: 140,
        opExDelta: -15,
        tdiDelta: -10,
        velocityDelta: 8,
        resilienceDelta: 14,
        complianceDelta: 12,
        trustDelta: { 'sh-arch-claire': 12, 'sh-esn-rajesh': 8 },
        affectedNodeIds: ['node-knowledge-base', 'node-onshore-eng'],
        durationRounds: 1,
        riskLevel: 'LOW',
      },
      {
        id: 'mo-init-reinsource',
        name: 'Réinternalisation Ciblée du Coeur Métier Souverain',
        category: 'MODERNIZATION',
        description: 'Recrutement de 8 ingénieurs et architectes seniors onshore pour reprendre la maîtrise des règles de calcul et de tarification.',
        capExCost: 380,
        opExDelta: 60,
        tdiDelta: -24,
        velocityDelta: 16,
        resilienceDelta: 28,
        complianceDelta: 15,
        trustDelta: { 'sh-arch-claire': 22, 'sh-cfo-julien': -14 },
        affectedNodeIds: ['node-core-logic', 'node-onshore-eng'],
        durationRounds: 2,
        riskLevel: 'MEDIUM',
      },
      {
        id: 'mo-init-bypass',
        name: 'Fast-Track Offshore Direct DB Writes',
        category: 'FEATURE_EXPEDITE',
        description: 'Autoriser l\'ESN à insérer directement les écritures dans la base de données sans passer par la passerelle de validation.',
        capExCost: 60,
        opExDelta: 45,
        tdiDelta: 25,
        velocityDelta: 24,
        resilienceDelta: -22,
        complianceDelta: -30,
        trustDelta: { 'sh-cfo-julien': 15, 'sh-arch-claire': -28, 'sh-esn-rajesh': 12 },
        affectedNodeIds: ['node-core-logic', 'node-data-vault'],
        durationRounds: 1,
        riskLevel: 'EXTREME',
      },
    ],
    tags: ['Offshore', 'Souveraineté', 'Architecture Guardrail', 'Dette Technique', 'Arbitrage Coûts'],
    author: 'GemSim Strategic Architecture Council',
    isDefault: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'scen-industrial-lyon',
    title: "Usine de Vénissieux : acquisition et intégration industrielle",
    industry: 'Industrie manufacturière / Équipements',
    domain: 'INDUSTRIAL',
    language: 'fr',
    currency: 'EUR',
    difficulty: 'EXECUTIVE',
    description: "Votre groupe vient de racheter l'usine de Vénissieux, un concurrent en difficulté. Vous avez quatre trimestres pour remettre l'outil à niveau, sécuriser les approvisionnements et livrer les synergies promises au conseil, sans casser le climat social ni la conformité environnementale.",
    businessContext: "Le site produit des pompes industrielles sur deux lignes : la ligne A (1998) tombe en panne chaque semaine, la ligne B est saturée. Un fournisseur unique livre 70 % des pièces moulées. L'inspection environnementale (DREAL) a relevé des écarts sur le traitement des effluents. Le conseil attend 12 % de synergies de coûts sur l'année ; les représentants du personnel craignent un plan social.",
    vocabulary: {
      nodeNoun: 'site',
      metrics: {
        technicalDebtIndex: { label: 'Vétusté industrielle', description: "Usure des équipements et retard de maintenance de l'usine rachetée." },
        deliveryVelocity: { label: 'Capacité de production', description: 'Volume livrable aux clients chaque trimestre.' },
        resilienceIndex: { label: "Résilience de la chaîne d'approvisionnement", description: 'Capacité à absorber pannes et ruptures fournisseurs.' },
        complianceScore: { label: 'Conformité HSE / environnement', description: 'Sécurité au travail, effluents, exigences de la DREAL.' },
        modernizedNodesCount: { label: 'Sites et lignes modernisés', description: 'Lignes, entrepôts ou systèmes remis à niveau.' },
        tco: { label: "Coût total de l'intégration", description: 'Investissements et dépassements cumulés.' },
      },
      layers: { BUSINESS: 'Clients & marché', APPLICATION: 'Production', DATA: 'Pilotage', INFRASTRUCTURE: 'Sites & logistique' },
      postures: {
        BYPASS_ARCH: { name: 'Cadence forcée (3x8 sans maintenance)', description: 'Volume immédiat, mais usure, accidents et non-conformités en hausse.' },
        BALANCED_AGILE: { name: 'Exploitation standard', description: 'Rythme normal, maintenance courante.' },
        STRICT_GOVERNANCE: { name: 'Qualité & sécurité renforcées', description: 'Contrôles systématiques : moins de volume, fiabilité et conformité élevées.' },
        ACCELERATED_MODERN: { name: 'Plan de transformation industrielle', description: 'Équipes dédiées à la remise à niveau sans arrêter la production.' },
      },
    },
    baselineMetrics: {
      tco: 2600,
      budgetRemaining: 1700,
      opEx: 600,
      capExSpent: 400,
      technicalDebtIndex: 70,
      deliveryVelocity: 45,
      stakeholderTrust: 50,
      resilienceIndex: 46,
      complianceScore: 58,
      modernizedNodesCount: 1,
    },
    winLossConditions: {
      maxTechnicalDebtIndex: 45,
      minStakeholderTrustAvg: 60,
      minDeliveryVelocity: 62,
      minResilienceIndex: 72,
      maxTCOBudget: 4900,
      targetCapabilitiesModernized: 4,
      minMarketShare: 32,
      minCumulativeProfit: 3800,
    },
    totalRounds: 4,
    maxInitiativesPerRound: 2,
    market: {
      unitCost: 6.4,
      fixedCosts: 700,
      unitsPerCapacityPoint: 10,
      cashRetention: 0.5,
      segments: [
        {
          id: 'seg-ind-oem', name: 'Industrie & automobile (grands comptes)',
          description: 'Gros volumes, acheteurs très attentifs au prix et aux délais de livraison.',
          baseDemand: 900, growth: 0.01, referencePrice: 8,
          priceSensitivity: 0.75, qualitySensitivity: 0.35, speedSensitivity: 0.6, reliabilitySensitivity: 0.45,
        },
        {
          id: 'seg-ind-rail', name: 'Ferroviaire & énergie',
          description: 'Pompes critiques sous cahier des charges strict : la qualité et la fiabilité priment sur le prix.',
          baseDemand: 500, growth: 0.03, referencePrice: 13,
          priceSensitivity: 0.3, qualitySensitivity: 0.8, speedSensitivity: 0.3, reliabilitySensitivity: 0.7,
        },
        {
          id: 'seg-ind-export', name: 'Export Moyen-Orient (dessalement)',
          description: "Marché en forte croissance, accessible après homologation et mise en place d'un agent local.",
          baseDemand: 380, growth: 0.07, referencePrice: 11,
          priceSensitivity: 0.5, qualitySensitivity: 0.55, speedSensitivity: 0.5, reliabilitySensitivity: 0.4,
          openAtStart: false, entryCost: 160,
        },
      ],
      rivals: [
        { id: 'riv-ind-grundmann', name: 'Grundmann Pumpen (premium allemand)', priceIndex: 1.06, quality: 74, aggressiveness: 0.15 },
        { id: 'riv-ind-asiaflow', name: 'AsiaFlow (bas coût)', priceIndex: 0.82, quality: 44, aggressiveness: 0.6, segmentIds: ['seg-ind-oem', 'seg-ind-export'] },
      ],
    },
    topology: {
      nodes: [
        {
          id: 'ind-line-a', name: 'Ligne A (1998)', layer: 'APPLICATION', archetype: 'TOWER',
          description: "Ligne d'usinage historique : pannes hebdomadaires, pièces détachées introuvables.",
          health: 38, technicalDebt: 84, criticalPath: true, costPerRound: 170,
          position: { x: -3, y: 2, z: 0 }, status: 'CRITICAL', dependencies: ['ind-supplier'],
          telemetry: { latencyMs: 820, throughputRps: 300, errorRatePercent: 6.5, failureRisk: 82 },
        },
        {
          id: 'ind-line-b', name: "Ligne B d'assemblage", layer: 'APPLICATION', archetype: 'TOWER',
          description: 'Ligne récente mais saturée à 96 % de sa capacité.',
          health: 66, technicalDebt: 48, criticalPath: true, costPerRound: 120,
          position: { x: 2, y: 2, z: 0 }, status: 'DEGRADED', dependencies: ['ind-line-a', 'ind-warehouse'],
          telemetry: { latencyMs: 260, throughputRps: 900, errorRatePercent: 1.8, failureRisk: 44 },
        },
        {
          id: 'ind-supplier', name: 'Fonderie fournisseur unique', layer: 'INFRASTRUCTURE', archetype: 'SLAB',
          description: 'Fournit 70 % des pièces moulées ; délais en hausse et situation financière fragile.',
          health: 52, technicalDebt: 66, criticalPath: true, costPerRound: 90,
          position: { x: -6, y: -2, z: 0 }, status: 'DEGRADED', dependencies: [],
          telemetry: { latencyMs: 600, throughputRps: 400, errorRatePercent: 3.2, failureRisk: 64 },
        },
        {
          id: 'ind-warehouse', name: 'Entrepôt régional', layer: 'INFRASTRUCTURE', archetype: 'SLAB',
          description: 'Stockage pièces et produits finis ; gestion manuelle des emplacements.',
          health: 60, technicalDebt: 58, criticalPath: false, costPerRound: 60,
          position: { x: 5, y: -2, z: 0 }, status: 'DEGRADED', dependencies: [],
          telemetry: { latencyMs: 300, throughputRps: 700, errorRatePercent: 1.4, failureRisk: 40 },
        },
        {
          id: 'ind-mes', name: 'MES / ERP du site', layer: 'DATA', archetype: 'DATABASE',
          description: "Système de pilotage de la production non relié à l'ERP du groupe : double saisie partout.",
          health: 55, technicalDebt: 72, criticalPath: true, costPerRound: 70,
          position: { x: 0, y: -4, z: 0 }, status: 'DEGRADED', dependencies: ['ind-line-a', 'ind-line-b'],
          telemetry: { latencyMs: 480, throughputRps: 500, errorRatePercent: 2.6, failureRisk: 58 },
        },
        {
          id: 'ind-effluents', name: 'Station de traitement des effluents', layer: 'INFRASTRUCTURE', archetype: 'DATABASE',
          description: "Installation sous-dimensionnée, épinglée par l'inspection environnementale.",
          health: 48, technicalDebt: 70, criticalPath: false, costPerRound: 45,
          position: { x: -2, y: -6, z: 0 }, status: 'DEGRADED', dependencies: ['ind-line-a'],
          telemetry: { latencyMs: 200, throughputRps: 200, errorRatePercent: 2.0, failureRisk: 55 },
        },
        {
          id: 'ind-customers', name: 'Grands comptes clients', layer: 'BUSINESS', archetype: 'SLAB',
          description: "Trois clients représentent 60 % du chiffre d'affaires ; pénalités de retard contractuelles.",
          health: 70, technicalDebt: 30, criticalPath: true, costPerRound: 25,
          position: { x: 0, y: 5, z: 0 }, status: 'HEALTHY', dependencies: ['ind-line-b'],
          telemetry: { latencyMs: 90, throughputRps: 1200, errorRatePercent: 0.6, failureRisk: 20 },
        },
        {
          id: 'ind-group-erp', name: 'ERP du groupe', layer: 'DATA', archetype: 'DATABASE',
          description: "Système de gestion du groupe acquéreur, cible de l'intégration.",
          health: 86, technicalDebt: 16, criticalPath: false, costPerRound: 30,
          position: { x: 4, y: -6, z: 0 }, status: 'MODERNIZED', dependencies: [],
          telemetry: { latencyMs: 60, throughputRps: 2000, errorRatePercent: 0.1, failureRisk: 6 },
        },
      ],
      edges: [
        { id: 'ie1', fromId: 'ind-supplier', toId: 'ind-line-a', protocol: 'Pièces moulées', bandwidthMbps: 300, status: 'BOTTLENECK', latencyMs: 600 },
        { id: 'ie2', fromId: 'ind-line-a', toId: 'ind-line-b', protocol: 'Sous-ensembles', bandwidthMbps: 400, status: 'BOTTLENECK', latencyMs: 420 },
        { id: 'ie3', fromId: 'ind-line-b', toId: 'ind-warehouse', protocol: 'Produits finis', bandwidthMbps: 800, status: 'NORMAL', latencyMs: 120 },
        { id: 'ie4', fromId: 'ind-warehouse', toId: 'ind-customers', protocol: 'Livraisons', bandwidthMbps: 800, status: 'NORMAL', latencyMs: 150 },
        { id: 'ie5', fromId: 'ind-mes', toId: 'ind-line-a', protocol: 'Ordres de fabrication', bandwidthMbps: 300, status: 'NORMAL', latencyMs: 200 },
        { id: 'ie6', fromId: 'ind-mes', toId: 'ind-group-erp', protocol: 'Double saisie manuelle', bandwidthMbps: 100, status: 'BOTTLENECK', latencyMs: 900 },
        { id: 'ie7', fromId: 'ind-line-a', toId: 'ind-effluents', protocol: 'Rejets de process', bandwidthMbps: 200, status: 'NORMAL', latencyMs: 80 },
      ],
    },
    stakeholders: [
      {
        id: 'sh-ind-cfo', name: 'Claire Morand', title: 'Directrice financière du groupe', role: 'Synergies & dette d’acquisition', avatar: '💼',
        personality: 'Rigoureuse, raisonne en flux de trésorerie et en engagements tenus.',
        bias: "Chaque euro investi doit contribuer aux 12 % de synergies promises au conseil.",
        hiddenAgenda: "Éviter une dépréciation du goodwill de l'acquisition au prochain arrêté des comptes.",
        negotiationTolerance: 40, baseTrust: 50,
        decisionWeights: { financialAcumen: 0.6, deliverySpeed: 0.15, architecturalRigor: 0.1, regulatoryCompliance: 0.15 },
        sampleDialogue: {
          greeting: 'Montrez-moi la trajectoire de synergies, trimestre par trimestre.',
          resistance: "Je ne finance pas un rétrofit sans jalon de gains mesurables.",
          concession: 'Phasez l’investissement avec un jalon de baisse des coûts d’exploitation et je débloque la deuxième tranche.',
        },
      },
      {
        id: 'sh-ind-coo', name: 'Karim Benali', title: 'Directeur industriel', role: 'Production & fiabilité des lignes', avatar: '🏭',
        personality: 'Homme de terrain, pragmatique, très attaché à la sécurité des équipes.',
        bias: 'La fiabilité des machines passe avant les tableaux de bord financiers.',
        hiddenAgenda: 'Obtenir la ligne A neuve pour en faire la vitrine industrielle du groupe.',
        negotiationTolerance: 55, baseTrust: 55,
        decisionWeights: { financialAcumen: 0.15, deliverySpeed: 0.35, architecturalRigor: 0.35, regulatoryCompliance: 0.15 },
        sampleDialogue: {
          greeting: 'Chaque panne de la ligne A me coûte une équipe complète à l’arrêt.',
          resistance: 'Forcer la cadence sans maintenance, c’est préparer le prochain accident.',
          concession: 'Donnez-moi le rétrofit de la ligne A et je vous garantis la capacité au trimestre 3.',
        },
      },
      {
        id: 'sh-ind-hr', name: 'Sophie Lambert', title: 'DRH et dialogue social', role: 'Climat social & compétences', avatar: '🤝',
        personality: 'Diplomate, à l’écoute, ferme sur les engagements pris auprès des salariés.',
        bias: "Aucune transformation ne tient sans l'adhésion des équipes et des représentants du personnel.",
        hiddenAgenda: 'Éviter un conflit social avant la négociation annuelle obligatoire.',
        negotiationTolerance: 50, baseTrust: 52,
        decisionWeights: { financialAcumen: 0.15, deliverySpeed: 0.15, architecturalRigor: 0.2, regulatoryCompliance: 0.5 },
        sampleDialogue: {
          greeting: 'Les équipes de Vénissieux attendent de savoir si elles ont un avenir dans le groupe.',
          resistance: 'Annoncer des 3x8 sans accord, c’est la grève assurée.',
          concession: 'Un plan de formation et un accord de méthode, et j’obtiens l’adhésion des représentants.',
        },
      },
      {
        id: 'sh-ind-hse', name: 'Thomas Girard', title: 'Responsable HSE & RSE', role: 'Sécurité, environnement, conformité', avatar: '🌿',
        personality: 'Méthodique, intransigeant sur la sécurité, sensible à l’image du groupe.',
        bias: 'Une non-conformité environnementale peut fermer le site, synergies ou pas.',
        hiddenAgenda: 'Faire de Vénissieux le premier site certifié ISO 14001 du groupe.',
        negotiationTolerance: 45, baseTrust: 48,
        decisionWeights: { financialAcumen: 0.1, deliverySpeed: 0.1, architecturalRigor: 0.3, regulatoryCompliance: 0.5 },
        sampleDialogue: {
          greeting: "La DREAL revient dans six mois. Elle ne reviendra pas pour discuter.",
          resistance: 'Pas de hausse de cadence tant que la station d’effluents n’est pas remise aux normes.',
          concession: 'Engagez la mise aux normes de la station et je soutiens votre plan devant le conseil.',
        },
      },
    ],
    roundEvents: [
      {
        roundNumber: 1, title: 'T1 : Retards en cascade chez la fonderie',
        description: 'Le fournisseur unique annonce six semaines de retard ; deux grands comptes menacent d’appliquer leurs pénalités.',
        type: 'VENDOR_EOL', severity: 'HIGH',
        immediateImpact: { budgetFine: 90, tdiSurge: 4, velocityPenalty: -10 },
        choices: [
          { id: 'ind-c1', text: 'Qualifier en urgence un second fondeur (double sourcing)', capExImpact: 110, tdiImpact: -4, velocityImpact: 4, trustImpact: { 'sh-ind-coo': 10, 'sh-ind-cfo': -4 }, nodeHealthImpacts: { 'ind-supplier': 15 } },
          { id: 'ind-c2', text: 'Payer les pénalités et attendre', capExImpact: 150, tdiImpact: 2, velocityImpact: -10, trustImpact: { 'sh-ind-cfo': -10, 'sh-ind-coo': -6 } },
        ],
      },
      {
        roundNumber: 2, title: 'T2 : Inspection environnementale inopinée',
        description: 'La DREAL constate des dépassements de rejets et met le site en demeure.',
        type: 'AUDIT', severity: 'HIGH',
        immediateImpact: { budgetFine: 160, tdiSurge: 0, velocityPenalty: -8 },
        choices: [
          { id: 'ind-c3', text: 'Plan d’action immédiat et mise aux normes provisoire', capExImpact: 140, tdiImpact: -4, velocityImpact: -4, trustImpact: { 'sh-ind-hse': 16, 'sh-ind-cfo': -4 } },
          { id: 'ind-c4', text: 'Contester la mise en demeure', capExImpact: 60, tdiImpact: 4, velocityImpact: 0, trustImpact: { 'sh-ind-hse': -18, 'sh-ind-hr': -6 } },
        ],
      },
      {
        roundNumber: 3, title: 'T3 : Incendie sur la ligne A',
        description: 'Un départ de feu sur un variateur hors d’âge immobilise la ligne A ; la ligne B tourne au ralenti faute de sous-ensembles.',
        type: 'CRISIS', severity: 'BLACK_SWAN',
        immediateImpact: { budgetFine: 220, tdiSurge: 8, velocityPenalty: -18, downedNodeIds: ['ind-line-a'] },
        choices: [
          { id: 'ind-c5', text: 'Remise en état sécurisée et sous-traitance temporaire', capExImpact: 180, tdiImpact: -6, velocityImpact: 6, trustImpact: { 'sh-ind-coo': 12, 'sh-ind-hse': 10 } },
          { id: 'ind-c6', text: 'Redémarrage rapide avec réparation de fortune', capExImpact: 70, tdiImpact: 10, velocityImpact: 8, trustImpact: { 'sh-ind-hse': -20, 'sh-ind-hr': -8 } },
        ],
      },
      {
        roundNumber: 4, title: 'T4 : Revue des synergies par le conseil',
        description: "Le conseil d'administration passe en revue les synergies, la sécurité et le climat social du site.",
        type: 'MARKET_SHIFT', severity: 'MEDIUM',
        immediateImpact: { budgetFine: 0, tdiSurge: 0, velocityPenalty: 0 },
        choices: [
          { id: 'ind-c7', text: 'Présenter le plan industriel consolidé', capExImpact: 60, tdiImpact: -2, velocityImpact: 4, trustImpact: { 'sh-ind-cfo': 8, 'sh-ind-coo': 8 } },
          { id: 'ind-c8', text: 'Geler les investissements pour afficher la trésorerie', capExImpact: -100, tdiImpact: 8, velocityImpact: -8, trustImpact: { 'sh-ind-cfo': 12, 'sh-ind-coo': -14 } },
        ],
      },
    ],
    initiativesCatalog: [
      {
        id: 'ind-init-retrofit', name: 'Rétrofit de la ligne A', category: 'CAPACITY_EXPANSION',
        description: 'Remplacement des commandes numériques, des variateurs et de la broche principale. Deux trimestres de chantier.',
        capExCost: 400, opExDelta: -45, tdiDelta: -24, velocityDelta: 16, resilienceDelta: 16, complianceDelta: 8,
        trustDelta: { 'sh-ind-coo': 16, 'sh-ind-cfo': -4 }, affectedNodeIds: ['ind-line-a', 'ind-line-b'], durationRounds: 2, riskLevel: 'HIGH',
      },
      {
        id: 'ind-init-mes', name: 'Intégration du MES à l’ERP groupe', category: 'OPERATIONS_EXCELLENCE',
        description: 'Fin de la double saisie : ordres de fabrication, stocks et achats pilotés dans l’ERP du groupe.',
        capExCost: 240, opExDelta: -25, tdiDelta: -14, velocityDelta: 12, resilienceDelta: 10, complianceDelta: 6,
        trustDelta: { 'sh-ind-cfo': 10, 'sh-ind-coo': 4 }, affectedNodeIds: ['ind-mes', 'ind-warehouse'], durationRounds: 1, riskLevel: 'MEDIUM',
      },
      {
        id: 'ind-init-sourcing', name: 'Double sourcing des pièces moulées', category: 'SOURCING_PARTNERSHIP',
        description: 'Qualification d’un second fondeur et contrat-cadre avec stock de sécurité.',
        capExCost: 180, opExDelta: 10, tdiDelta: -10, velocityDelta: 6, resilienceDelta: 22, complianceDelta: 2,
        trustDelta: { 'sh-ind-coo': 8, 'sh-ind-cfo': -2 }, affectedNodeIds: ['ind-supplier'], durationRounds: 1, riskLevel: 'LOW',
      },
      {
        id: 'ind-init-hse', name: 'Mise aux normes HSE et station d’effluents', category: 'RISK_MITIGATION',
        description: 'Nouvelle station de traitement, audits sécurité et démarche ISO 14001.',
        capExCost: 220, opExDelta: -5, tdiDelta: -12, velocityDelta: -4, resilienceDelta: 14, complianceDelta: 30,
        trustDelta: { 'sh-ind-hse': 18, 'sh-ind-hr': 6 }, affectedNodeIds: ['ind-effluents'], durationRounds: 1, riskLevel: 'LOW',
      },
      {
        id: 'ind-init-people', name: 'Accord de méthode et plan de compétences', category: 'PEOPLE_CHANGE',
        description: 'Accord avec les représentants du personnel, formation aux nouveaux équipements, polyvalence.',
        capExCost: 140, opExDelta: 5, tdiDelta: -8, velocityDelta: 10, resilienceDelta: 8, complianceDelta: 10,
        trustDelta: { 'sh-ind-hr': 18, 'sh-ind-coo': 6 }, affectedNodeIds: ['ind-line-b'], durationRounds: 1, riskLevel: 'LOW',
      },
      {
        id: 'ind-init-3x8', name: 'Passage en 3x8 sans maintenance préventive', category: 'QUICK_WIN',
        description: 'Faire tourner les lignes jour et nuit en sacrifiant les arrêts de maintenance.',
        capExCost: 80, opExDelta: 45, tdiDelta: 22, velocityDelta: 24, resilienceDelta: -18, complianceDelta: -26,
        trustDelta: { 'sh-ind-cfo': 8, 'sh-ind-hr': -22, 'sh-ind-hse': -16 }, affectedNodeIds: ['ind-line-a', 'ind-line-b'], durationRounds: 1, riskLevel: 'EXTREME',
      },
    ],
    tags: ['Industrie', 'Acquisition', 'Intégration', 'Supply chain', 'HSE'],
    author: 'GemSim Industrial Working Group',
    isDefault: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'scen-expansion-dumas',
    title: "Maison Dumas : conquête de l'Allemagne et du Canada",
    industry: 'Biens de consommation / Art de la table',
    domain: 'MARKET_EXPANSION',
    language: 'fr',
    currency: 'EUR',
    difficulty: 'EXECUTIVE',
    description: "Maison Dumas, fabricant familial d'ustensiles de cuisine haut de gamme à Thiers, plafonne en France. Le conseil vous confie quatre trimestres pour ouvrir l'Allemagne et le Canada, défendre la marque face au bas coût en ligne et prouver que l'expansion crée de la valeur au lieu de la détruire.",
    businessContext: "L'entreprise réalise l'essentiel de ses ventes en France, en magasins spécialisés et sur son site. Les marketplaces européennes progressent vite mais sont envahies par des copies bon marché. L'Allemagne exige des certifications contact alimentaire et un service irréprochable ; le Canada est en forte croissance mais loin. L'ERP ne gère qu'un pays, le site n'est pas traduit, l'atelier tourne à 85 % de sa capacité. Un concurrent allemand premium et un acteur asiatique bas coût vous attendent.",
    vocabulary: {
      nodeNoun: 'maillon',
      metrics: {
        technicalDebtIndex: { label: "Dette d'intégration", description: "Écart entre vos nouvelles implantations et un modèle opératoire qui tient : processus, systèmes, équipes." },
        deliveryVelocity: { label: 'Capacité de service', description: 'Commandes que vous pouvez fabriquer et livrer chaque trimestre. Elle plafonne vos ventes.' },
        resilienceIndex: { label: 'Robustesse opérationnelle', description: 'Capacité à tenir les délais malgré les aléas logistiques et les pics de demande.' },
        complianceScore: { label: 'Conformité produits & fiscale', description: 'Normes contact alimentaire, étiquetage, TVA et douanes de chaque pays.' },
        modernizedNodesCount: { label: 'Implantations intégrées', description: 'Implantations alignées sur le modèle opératoire cible.' },
        tco: { label: "Coût total de l'expansion", description: 'Investissements et dépassements cumulés.' },
      },
      layers: { BUSINESS: 'Marchés & marque', APPLICATION: 'Opérations', DATA: 'Systèmes & conformité', INFRASTRUCTURE: 'Implantations & logistique' },
      postures: {
        BYPASS_ARCH: { name: 'Croissance à tout prix', description: 'Ouvrir vite sans processus : ventes immédiates, dette d’intégration et litiges en hausse.' },
        BALANCED_AGILE: { name: 'Expansion pas à pas', description: 'Rythme standard, intégration au fil de l’eau.' },
        STRICT_GOVERNANCE: { name: 'Expansion sous contrôle', description: 'Chaque pays validé (juridique, fiscal, qualité) avant d’accélérer : plus lent, plus sûr.' },
        ACCELERATED_MODERN: { name: 'Plateforme internationale', description: 'Construire le socle commun (ERP, logistique, équipes) pendant la conquête.' },
      },
    },
    baselineMetrics: {
      tco: 1800,
      budgetRemaining: 1600,
      opEx: 480,
      capExSpent: 300,
      technicalDebtIndex: 62,
      deliveryVelocity: 50,
      stakeholderTrust: 52,
      resilienceIndex: 50,
      complianceScore: 55,
      modernizedNodesCount: 1,
    },
    winLossConditions: {
      maxTechnicalDebtIndex: 45,
      minStakeholderTrustAvg: 60,
      minDeliveryVelocity: 62,
      minResilienceIndex: 70,
      maxTCOBudget: 4400,
      targetCapabilitiesModernized: 4,
      minMarketShare: 30,
      minCumulativeProfit: 3200,
    },
    totalRounds: 4,
    maxInitiativesPerRound: 2,
    market: {
      unitCost: 0.15,
      fixedCosts: 500,
      unitsPerCapacityPoint: 300,
      cashRetention: 0.5,
      segments: [
        {
          id: 'seg-exp-fr', name: 'France (magasins spécialisés & site)',
          description: 'Marché historique, mature : la marque y est connue, la qualité compte autant que le prix.',
          baseDemand: 15000, growth: 0, referencePrice: 0.24,
          priceSensitivity: 0.5, qualitySensitivity: 0.6, speedSensitivity: 0.4, reliabilitySensitivity: 0.4,
        },
        {
          id: 'seg-exp-online', name: 'Marketplaces européennes',
          description: 'Volume en croissance, clients très sensibles au prix et aux délais de livraison.',
          baseDemand: 12000, growth: 0.05, referencePrice: 0.19,
          priceSensitivity: 0.85, qualitySensitivity: 0.25, speedSensitivity: 0.7, reliabilitySensitivity: 0.35,
        },
        {
          id: 'seg-exp-de', name: 'Allemagne',
          description: 'Grand marché exigeant : certifications, qualité et service avant tout. Entrée : distributeur, traduction, homologation.',
          baseDemand: 13000, growth: 0.03, referencePrice: 0.27,
          priceSensitivity: 0.4, qualitySensitivity: 0.85, speedSensitivity: 0.4, reliabilitySensitivity: 0.6,
          openAtStart: false, entryCost: 200,
        },
        {
          id: 'seg-exp-ca', name: 'Canada',
          description: 'Marché en forte croissance, attiré par le savoir-faire français. Entrée : agent à Montréal, douane, site bilingue.',
          baseDemand: 8000, growth: 0.07, referencePrice: 0.29,
          priceSensitivity: 0.45, qualitySensitivity: 0.55, speedSensitivity: 0.45, reliabilitySensitivity: 0.5,
          openAtStart: false, entryCost: 240,
        },
      ],
      rivals: [
        { id: 'riv-exp-kochwerk', name: 'Kochwerk (premium allemand)', priceIndex: 1.1, quality: 78, aggressiveness: 0.1, segmentIds: ['seg-exp-fr', 'seg-exp-de'] },
        { id: 'riv-exp-panasia', name: 'PanAsia Cook (bas coût)', priceIndex: 0.78, quality: 40, aggressiveness: 0.5 },
        { id: 'riv-exp-northfield', name: 'Northfield Cookware (leader canadien)', priceIndex: 1, quality: 65, aggressiveness: 0.3, segmentIds: ['seg-exp-ca'] },
      ],
    },
    topology: {
      nodes: [
        {
          id: 'exp-plant', name: 'Atelier de Thiers', layer: 'APPLICATION', archetype: 'TOWER',
          description: 'Forge et polissage à 85 % de capacité ; savoir-faire rare, équipements des années 2000.',
          health: 62, technicalDebt: 56, criticalPath: true, costPerRound: 130,
          position: { x: -3, y: 2, z: 0 }, status: 'DEGRADED', dependencies: ['exp-erp'],
          telemetry: { latencyMs: 300, throughputRps: 600, errorRatePercent: 1.6, failureRisk: 42 },
        },
        {
          id: 'exp-ecom', name: 'Site e-commerce', layer: 'APPLICATION', archetype: 'SLAB',
          description: 'Site en français uniquement, paiement et livraison pensés pour la France.',
          health: 58, technicalDebt: 64, criticalPath: true, costPerRound: 60,
          position: { x: 2, y: 2, z: 0 }, status: 'DEGRADED', dependencies: ['exp-erp', 'exp-3pl'],
          telemetry: { latencyMs: 420, throughputRps: 800, errorRatePercent: 2.2, failureRisk: 52 },
        },
        {
          id: 'exp-erp', name: 'ERP & gestion des stocks', layer: 'DATA', archetype: 'DATABASE',
          description: 'Mono-pays, mono-devise : chaque export passe par des tableurs.',
          health: 50, technicalDebt: 70, criticalPath: true, costPerRound: 70,
          position: { x: 0, y: -4, z: 0 }, status: 'DEGRADED', dependencies: [],
          telemetry: { latencyMs: 520, throughputRps: 400, errorRatePercent: 3, failureRisk: 60 },
        },
        {
          id: 'exp-3pl', name: 'Entrepôt de Clermont', layer: 'INFRASTRUCTURE', archetype: 'SLAB',
          description: 'Entrepôt unique, préparation manuelle ; délais de 6 jours vers l’Allemagne.',
          health: 60, technicalDebt: 54, criticalPath: false, costPerRound: 60,
          position: { x: 5, y: -2, z: 0 }, status: 'DEGRADED', dependencies: [],
          telemetry: { latencyMs: 380, throughputRps: 700, errorRatePercent: 1.8, failureRisk: 44 },
        },
        {
          id: 'exp-de-partner', name: 'Distributeur allemand', layer: 'INFRASTRUCTURE', archetype: 'SLAB',
          description: 'Partenaire pressenti à Cologne, exige des certifications et un SAV en allemand.',
          health: 56, technicalDebt: 60, criticalPath: false, costPerRound: 40,
          position: { x: 7, y: 1, z: 0 }, status: 'DEGRADED', dependencies: ['exp-3pl'],
          telemetry: { latencyMs: 450, throughputRps: 300, errorRatePercent: 2.4, failureRisk: 50 },
        },
        {
          id: 'exp-ca-agent', name: 'Agent commercial à Montréal', layer: 'INFRASTRUCTURE', archetype: 'SLAB',
          description: 'Un agent indépendant, aucun stock local ; douane gérée au cas par cas.',
          health: 54, technicalDebt: 62, criticalPath: false, costPerRound: 35,
          position: { x: -7, y: 1, z: 0 }, status: 'DEGRADED', dependencies: ['exp-erp'],
          telemetry: { latencyMs: 600, throughputRps: 200, errorRatePercent: 2.8, failureRisk: 54 },
        },
        {
          id: 'exp-brand', name: 'Marque & clients fidèles', layer: 'BUSINESS', archetype: 'SLAB',
          description: 'Une marque centenaire, très bien notée en France, inconnue ailleurs.',
          health: 84, technicalDebt: 24, criticalPath: true, costPerRound: 25,
          position: { x: 0, y: 5, z: 0 }, status: 'MODERNIZED', dependencies: ['exp-ecom'],
          telemetry: { latencyMs: 80, throughputRps: 1500, errorRatePercent: 0.3, failureRisk: 10 },
        },
        {
          id: 'exp-compliance', name: 'Conformité produits & fiscalité', layer: 'DATA', archetype: 'DATABASE',
          description: 'Normes contact alimentaire, étiquetage multilingue, TVA à l’export : traités à la main.',
          health: 52, technicalDebt: 66, criticalPath: false, costPerRound: 40,
          position: { x: -2, y: -6, z: 0 }, status: 'DEGRADED', dependencies: ['exp-erp'],
          telemetry: { latencyMs: 300, throughputRps: 200, errorRatePercent: 2.5, failureRisk: 56 },
        },
      ],
      edges: [
        { id: 'xe1', fromId: 'exp-erp', toId: 'exp-plant', protocol: 'Ordres de fabrication', bandwidthMbps: 300, status: 'NORMAL', latencyMs: 300 },
        { id: 'xe2', fromId: 'exp-plant', toId: 'exp-3pl', protocol: 'Produits finis', bandwidthMbps: 500, status: 'BOTTLENECK', latencyMs: 400 },
        { id: 'xe3', fromId: 'exp-3pl', toId: 'exp-de-partner', protocol: 'Expéditions UE', bandwidthMbps: 300, status: 'BOTTLENECK', latencyMs: 600 },
        { id: 'xe4', fromId: 'exp-erp', toId: 'exp-ca-agent', protocol: 'Commandes par tableur', bandwidthMbps: 100, status: 'BOTTLENECK', latencyMs: 900 },
        { id: 'xe5', fromId: 'exp-ecom', toId: 'exp-brand', protocol: 'Expérience client', bandwidthMbps: 800, status: 'NORMAL', latencyMs: 120 },
        { id: 'xe6', fromId: 'exp-erp', toId: 'exp-compliance', protocol: 'Déclarations', bandwidthMbps: 100, status: 'NORMAL', latencyMs: 500 },
        { id: 'xe7', fromId: 'exp-3pl', toId: 'exp-ecom', protocol: 'Disponibilité stock', bandwidthMbps: 300, status: 'NORMAL', latencyMs: 250 },
      ],
    },
    stakeholders: [
      {
        id: 'sh-exp-ceo', name: 'Hélène Dumas', title: 'Présidente et actionnaire familiale', role: 'Vision & patrimoine de la marque', avatar: '👑',
        personality: 'Ambitieuse pour la marque, attachée à l’héritage familial, impatiente face aux lenteurs.',
        bias: 'La marque doit devenir européenne avant que les concurrents ne prennent la place.',
        hiddenAgenda: 'Préparer une entrée au capital d’un fonds sans perdre le contrôle familial.',
        negotiationTolerance: 50, baseTrust: 55,
        decisionWeights: { financialAcumen: 0.3, deliverySpeed: 0.4, architecturalRigor: 0.15, regulatoryCompliance: 0.15 },
        sampleDialogue: {
          greeting: 'Mon arrière-grand-père vendait à Berlin en 1920. Je veux y revenir.',
          resistance: 'Si vous me proposez encore six mois d’études, Kochwerk aura pris le marché.',
          concession: 'Montrez-moi une première vitrine en Allemagne ce trimestre et je vous laisse construire le socle.',
        },
      },
      {
        id: 'sh-exp-cfo', name: 'Marc Vidal', title: 'Directeur administratif et financier', role: 'Rentabilité & trésorerie', avatar: '💼',
        personality: 'Prudent, chiffré, méfiant envers les promesses de croissance sans marge.',
        bias: 'Un chiffre d’affaires acheté à perte détruit de la valeur.',
        hiddenAgenda: 'Respecter les covenants bancaires pour éviter une renégociation de la dette.',
        negotiationTolerance: 40, baseTrust: 50,
        decisionWeights: { financialAcumen: 0.6, deliverySpeed: 0.1, architecturalRigor: 0.15, regulatoryCompliance: 0.15 },
        sampleDialogue: {
          greeting: 'Quel est le seuil de rentabilité de chaque pays ?',
          resistance: 'Brader nos prix sur les marketplaces, c’est vendre notre marque au rabais.',
          concession: 'Un pays à la fois, avec un jalon de marge, et je finance le suivant.',
        },
      },
      {
        id: 'sh-exp-export', name: 'Julia Weber', title: 'Directrice export', role: 'Conquête commerciale', avatar: '🌍',
        personality: 'Énergique, réseau solide en Allemagne, raisonne en parts de marché.',
        bias: 'Sans présence locale et sans marketing, aucune marque ne perce à l’étranger.',
        hiddenAgenda: 'Obtenir la direction d’une future filiale allemande.',
        negotiationTolerance: 55, baseTrust: 54,
        decisionWeights: { financialAcumen: 0.15, deliverySpeed: 0.5, architecturalRigor: 0.1, regulatoryCompliance: 0.25 },
        sampleDialogue: {
          greeting: 'Le distributeur de Cologne attend notre réponse avant la fin du mois.',
          resistance: 'Sans budget marketing, nous resterons invisibles en Allemagne.',
          concession: 'Financez la certification et la traduction, je vous signe le distributeur.',
        },
      },
      {
        id: 'sh-exp-ops', name: 'Nicolas Faure', title: 'Directeur des opérations et des systèmes', role: 'Atelier, logistique, ERP', avatar: '⚙️',
        personality: 'Méthodique, protecteur de l’atelier, alerte sur la capacité.',
        bias: 'Vendre ce qu’on ne sait pas livrer, c’est perdre le client deux fois.',
        hiddenAgenda: 'Obtenir l’automatisation du polissage pour soulager les équipes.',
        negotiationTolerance: 50, baseTrust: 50,
        decisionWeights: { financialAcumen: 0.15, deliverySpeed: 0.25, architecturalRigor: 0.45, regulatoryCompliance: 0.15 },
        sampleDialogue: {
          greeting: 'L’atelier est à 85 % ; au-delà, les délais explosent.',
          resistance: 'Ouvrir deux pays avec un ERP mono-pays, c’est l’erreur garantie.',
          concession: 'Donnez-moi l’ERP multi-pays et je tiens les délais partout.',
        },
      },
    ],
    roundEvents: [
      {
        roundNumber: 1, title: 'T1 : Copies de vos poêles sur les marketplaces',
        description: 'Des contrefaçons à prix cassé apparaissent sous votre nom ; les avis clients chutent.',
        type: 'MARKET_SHIFT', severity: 'HIGH',
        immediateImpact: { budgetFine: 90, tdiSurge: 4, velocityPenalty: -8 },
        choices: [
          { id: 'exp-c1', text: 'Action juridique et programme de marque protégée sur les plateformes', capExImpact: 110, tdiImpact: -2, velocityImpact: 2, trustImpact: { 'sh-exp-ceo': 10, 'sh-exp-cfo': -4 }, nodeHealthImpacts: { 'exp-brand': 8 } },
          { id: 'exp-c2', text: 'Baisser vos prix en ligne pour couper l’herbe sous le pied', capExImpact: 60, tdiImpact: 4, velocityImpact: 4, trustImpact: { 'sh-exp-cfo': -12, 'sh-exp-export': 6 } },
        ],
      },
      {
        roundNumber: 2, title: 'T2 : Contrôle des normes contact alimentaire en Allemagne',
        description: 'Un laboratoire mandaté par une association de consommateurs teste vos revêtements.',
        type: 'AUDIT', severity: 'HIGH',
        immediateImpact: { budgetFine: 150, tdiSurge: 2, velocityPenalty: -8 },
        choices: [
          { id: 'exp-c3', text: 'Faire certifier toute la gamme par un laboratoire accrédité', capExImpact: 130, tdiImpact: -4, velocityImpact: -2, trustImpact: { 'sh-exp-export': 12, 'sh-exp-ops': 6 } },
          { id: 'exp-c4', text: 'Retirer temporairement les références contestées', capExImpact: 50, tdiImpact: 2, velocityImpact: -8, trustImpact: { 'sh-exp-export': -10, 'sh-exp-ceo': -6 } },
        ],
      },
      {
        roundNumber: 3, title: 'T3 : Grève portuaire et pic de commandes',
        description: 'Une grève bloque les conteneurs vers le Canada au moment d’un pic de commandes saisonnier.',
        type: 'DISRUPTION', severity: 'BLACK_SWAN',
        immediateImpact: { budgetFine: 200, tdiSurge: 8, velocityPenalty: -16, downedNodeIds: ['exp-ca-agent'] },
        choices: [
          { id: 'exp-c5', text: 'Fret aérien ciblé et transparence auprès des clients', capExImpact: 170, tdiImpact: -4, velocityImpact: 6, trustImpact: { 'sh-exp-export': 10, 'sh-exp-cfo': -6 } },
          { id: 'exp-c6', text: 'Promettre des délais intenables pour ne perdre aucune commande', capExImpact: 40, tdiImpact: 10, velocityImpact: 8, trustImpact: { 'sh-exp-ops': -16, 'sh-exp-ceo': -4 } },
        ],
      },
      {
        roundNumber: 4, title: 'T4 : Un fonds propose d’entrer au capital',
        description: 'Un fonds de croissance évalue Maison Dumas : il regarde la marge, la part de marché et la solidité opérationnelle.',
        type: 'MARKET_SHIFT', severity: 'MEDIUM',
        immediateImpact: { budgetFine: 0, tdiSurge: 0, velocityPenalty: 0 },
        choices: [
          { id: 'exp-c7', text: 'Présenter un plan de croissance rentable et documenté', capExImpact: 60, tdiImpact: -2, velocityImpact: 4, trustImpact: { 'sh-exp-ceo': 10, 'sh-exp-cfo': 8 } },
          { id: 'exp-c8', text: 'Gonfler les prévisions pour maximiser la valorisation', capExImpact: 0, tdiImpact: 6, velocityImpact: 0, trustImpact: { 'sh-exp-cfo': -14, 'sh-exp-ceo': 6 } },
        ],
      },
    ],
    initiativesCatalog: [
      {
        id: 'exp-init-erp', name: 'ERP multi-pays et stocks unifiés', category: 'OPERATIONS_EXCELLENCE',
        description: 'Multi-devise, multi-TVA, stocks visibles partout. Deux trimestres de déploiement.',
        capExCost: 360, opExDelta: -30, tdiDelta: -22, velocityDelta: 14, resilienceDelta: 14, complianceDelta: 10,
        trustDelta: { 'sh-exp-ops': 16, 'sh-exp-cfo': 4 }, affectedNodeIds: ['exp-erp', 'exp-ca-agent'], durationRounds: 2, riskLevel: 'HIGH',
      },
      {
        id: 'exp-init-localize', name: 'Site localisé et paiements locaux', category: 'MARKET_EXPANSION',
        description: 'Site en allemand et en anglais canadien, moyens de paiement et livraison locaux.',
        capExCost: 200, opExDelta: 10, tdiDelta: -12, velocityDelta: 12, resilienceDelta: 6, complianceDelta: 8,
        trustDelta: { 'sh-exp-export': 12, 'sh-exp-ceo': 6 }, affectedNodeIds: ['exp-ecom'], durationRounds: 1, riskLevel: 'MEDIUM',
      },
      {
        id: 'exp-init-3pl', name: 'Partenaire logistique européen', category: 'SOURCING_PARTNERSHIP',
        description: 'Stock avancé près de Cologne, livraison en 48 h en Allemagne et au Benelux.',
        capExCost: 180, opExDelta: 15, tdiDelta: -10, velocityDelta: 10, resilienceDelta: 18, complianceDelta: 2,
        trustDelta: { 'sh-exp-ops': 8, 'sh-exp-export': 6 }, affectedNodeIds: ['exp-3pl', 'exp-de-partner'], durationRounds: 1, riskLevel: 'LOW',
      },
      {
        id: 'exp-init-compliance', name: 'Certification produits et fiscalité export', category: 'RISK_MITIGATION',
        description: 'Certification contact alimentaire, étiquetage multilingue, guichet unique de TVA.',
        capExCost: 160, opExDelta: -5, tdiDelta: -10, velocityDelta: -2, resilienceDelta: 6, complianceDelta: 28,
        trustDelta: { 'sh-exp-export': 10, 'sh-exp-cfo': 4 }, affectedNodeIds: ['exp-compliance'], durationRounds: 1, riskLevel: 'LOW',
      },
      {
        id: 'exp-init-people', name: 'Équipes locales et formation', category: 'PEOPLE_CHANGE',
        description: 'Un responsable pays en Allemagne, un SAV bilingue, formation de l’agent canadien.',
        capExCost: 150, opExDelta: 10, tdiDelta: -8, velocityDelta: 10, resilienceDelta: 8, complianceDelta: 8,
        trustDelta: { 'sh-exp-export': 14, 'sh-exp-ops': 4 }, affectedNodeIds: ['exp-de-partner', 'exp-ca-agent'], durationRounds: 1, riskLevel: 'LOW',
      },
      {
        id: 'exp-init-plant', name: "Automatisation du polissage à l'atelier", category: 'CAPACITY_EXPANSION',
        description: 'Cellule robotisée de polissage : plus de capacité, moins de troubles musculo-squelettiques.',
        capExCost: 280, opExDelta: -20, tdiDelta: -14, velocityDelta: 18, resilienceDelta: 8, complianceDelta: 4,
        trustDelta: { 'sh-exp-ops': 12, 'sh-exp-cfo': -4 }, affectedNodeIds: ['exp-plant'], durationRounds: 1, riskLevel: 'MEDIUM',
      },
      {
        id: 'exp-init-blitz', name: 'Lancement éclair sur six marketplaces', category: 'QUICK_WIN',
        description: 'Ouvrir six pays en ligne en un mois, sans traduction ni conformité vérifiée.',
        capExCost: 90, opExDelta: 40, tdiDelta: 22, velocityDelta: 24, resilienceDelta: -16, complianceDelta: -24,
        trustDelta: { 'sh-exp-ceo': 8, 'sh-exp-cfo': -10, 'sh-exp-ops': -14 }, affectedNodeIds: ['exp-ecom', 'exp-compliance'], durationRounds: 1, riskLevel: 'EXTREME',
      },
    ],
    tags: ['Expansion internationale', 'Marché', 'Concurrence', 'PME', 'Marque'],
    author: 'GemSim Strategy Working Group',
    isDefault: true,
    createdAt: new Date().toISOString(),
  },
];
