// ============================================================================
// GEMSIM: DEFAULT SEED SCENARIOS
// Preloaded Enterprise Case Studies for Immediate Playability
// ============================================================================

import { Scenario } from '../types/index.js';

export const SEED_SCENARIOS: Scenario[] = [
  {
    id: 'scen-fintech-neotitan',
    title: 'Project NeoTitan: Core Banking Modernization',
    industry: 'Financial Services & Digital Banking',
    difficulty: 'INTERMEDIATE',
    description: 'Lead NeoTitan Bank through a 4-quarter modernization saga. Balance rapid neobank feature delivery with legacy mainframe decoupling, PCI-DSS compliance, and zero-downtime reliability.',
    businessContext: 'NeoTitan Bank serves 12M retail and commercial accounts. Core transaction clearing runs on a 25-year-old COBOL mainframe monolith. A competitor neobank is acquiring 150K users/month with instant virtual card issuing, while NeoTitan takes 4 days to settle transactions. Technical debt has reached 72%, and maintenance consumes 68% of IT budget.',
    baselineMetrics: {
      tco: 2400,
      budgetRemaining: 1500,
      opEx: 580,
      capExSpent: 400,
      technicalDebtIndex: 72,
      deliveryVelocity: 44,
      stakeholderTrust: 52,
      resilienceIndex: 48,
      complianceScore: 65,
      modernizedNodesCount: 1,
    },
    winLossConditions: {
      maxTechnicalDebtIndex: 45,
      minStakeholderTrustAvg: 60,
      minDeliveryVelocity: 68,
      minResilienceIndex: 72,
      maxTCOBudget: 4800,
      targetCapabilitiesModernized: 4,
    },
    totalRounds: 4,
    topology: {
      nodes: [
        {
          id: 'node-biz-app',
          name: 'Mobile Banking & Card Controls',
          layer: 'BUSINESS',
          description: 'Customer digital experience for iOS, Android, and Web portals.',
          health: 78,
          technicalDebt: 28,
          criticalPath: true,
          costPerRound: 55,
          position: { x: -6, y: 5, z: 0 },
          status: 'HEALTHY',
          dependencies: ['node-api-gw'],
          telemetry: { latencyMs: 45, throughputRps: 2800, errorRatePercent: 0.1, failureRisk: 16 },
        },
        {
          id: 'node-biz-lending',
          name: 'Commercial Lending & Risk Portal',
          layer: 'BUSINESS',
          description: 'Underwriting and commercial credit approvals.',
          health: 62,
          technicalDebt: 58,
          criticalPath: false,
          costPerRound: 65,
          position: { x: 6, y: 5, z: 0 },
          status: 'DEGRADED',
          dependencies: ['node-api-gw', 'node-legacy-core'],
          telemetry: { latencyMs: 320, throughputRps: 450, errorRatePercent: 1.4, failureRisk: 42 },
        },
        {
          id: 'node-api-gw',
          name: 'Zero-Trust API Gateway',
          layer: 'APPLICATION',
          description: 'Identity tokenization, rate limiting, and mTLS proxy.',
          health: 82,
          technicalDebt: 22,
          criticalPath: true,
          costPerRound: 40,
          position: { x: -4, y: 2, z: 0 },
          status: 'HEALTHY',
          dependencies: ['node-legacy-core', 'node-mod-services'],
          telemetry: { latencyMs: 14, throughputRps: 4200, errorRatePercent: 0.02, failureRisk: 10 },
        },
        {
          id: 'node-legacy-core',
          name: 'Mainframe Core Banking Monolith',
          layer: 'APPLICATION',
          description: 'Single monolithic ledger handling account balances, interest calculations, and batch clearing.',
          health: 38,
          technicalDebt: 82,
          criticalPath: true,
          costPerRound: 180,
          position: { x: 0, y: 2, z: 0 },
          status: 'CRITICAL',
          dependencies: ['node-db-mainframe', 'node-infra-onprem'],
          telemetry: { latencyMs: 820, throughputRps: 650, errorRatePercent: 4.2, failureRisk: 88 },
        },
        {
          id: 'node-mod-services',
          name: 'Payments Microservices (Strangler)',
          layer: 'APPLICATION',
          description: 'Decoupled domain services handling instant P2P payments and push notifications.',
          health: 88,
          technicalDebt: 15,
          criticalPath: false,
          costPerRound: 55,
          position: { x: 5, y: 2, z: 0 },
          status: 'MODERNIZED',
          dependencies: ['node-kafka-bus', 'node-infra-cloud'],
          telemetry: { latencyMs: 25, throughputRps: 3100, errorRatePercent: 0.05, failureRisk: 12 },
        },
        {
          id: 'node-db-mainframe',
          name: 'Hierarchical DB2 Mainframe Storage',
          layer: 'DATA',
          description: 'Legacy relational database with table locks and batch-night freeze windows.',
          health: 44,
          technicalDebt: 76,
          criticalPath: true,
          costPerRound: 110,
          position: { x: -2, y: -2, z: 0 },
          status: 'CRITICAL',
          dependencies: ['node-infra-onprem'],
          telemetry: { latencyMs: 460, throughputRps: 950, errorRatePercent: 2.8, failureRisk: 74 },
        },
        {
          id: 'node-kafka-bus',
          name: 'Kafka Real-Time Financial Ledger',
          layer: 'DATA',
          description: 'Distributed immutable event log for real-time auditability and ledger streaming.',
          health: 94,
          technicalDebt: 10,
          criticalPath: false,
          costPerRound: 45,
          position: { x: 4, y: -2, z: 0 },
          status: 'MODERNIZED',
          dependencies: ['node-infra-cloud'],
          telemetry: { latencyMs: 8, throughputRps: 8400, errorRatePercent: 0.01, failureRisk: 6 },
        },
        {
          id: 'node-infra-onprem',
          name: 'Tier-4 Legacy On-Premises Datacenter',
          layer: 'INFRASTRUCTURE',
          description: 'Fixed capacity server racks, annual hardware licensing, high power costs.',
          health: 56,
          technicalDebt: 64,
          criticalPath: true,
          costPerRound: 120,
          position: { x: -3, y: -5, z: 0 },
          status: 'DEGRADED',
          dependencies: [],
          telemetry: { latencyMs: 95, throughputRps: 3800, errorRatePercent: 0.8, failureRisk: 48 },
        },
        {
          id: 'node-infra-cloud',
          name: 'Cloud Kubernetes Multi-Zone Mesh',
          layer: 'INFRASTRUCTURE',
          description: 'Elastic multi-region infrastructure with automated failover and sub-second auto-scaling.',
          health: 92,
          technicalDebt: 12,
          criticalPath: false,
          costPerRound: 70,
          position: { x: 3, y: -5, z: 0 },
          status: 'MODERNIZED',
          dependencies: [],
          telemetry: { latencyMs: 18, throughputRps: 9200, errorRatePercent: 0.02, failureRisk: 8 },
        },
      ],
      edges: [
        { id: 'e1', fromId: 'node-biz-app', toId: 'node-api-gw', protocol: 'HTTPS/REST', bandwidthMbps: 2500, status: 'NORMAL', latencyMs: 20 },
        { id: 'e2', fromId: 'node-biz-lending', toId: 'node-legacy-core', protocol: 'MQ Series', bandwidthMbps: 350, status: 'BOTTLENECK', latencyMs: 340 },
        { id: 'e3', fromId: 'node-api-gw', toId: 'node-legacy-core', protocol: 'SNA / TCP Gateway', bandwidthMbps: 400, status: 'BOTTLENECK', latencyMs: 420 },
        { id: 'e4', fromId: 'node-api-gw', toId: 'node-mod-services', protocol: 'gRPC HTTP/2', bandwidthMbps: 3000, status: 'OPTIMIZED', latencyMs: 12 },
        { id: 'e5', fromId: 'node-legacy-core', toId: 'node-db-mainframe', protocol: 'Internal Bus', bandwidthMbps: 600, status: 'BOTTLENECK', latencyMs: 380 },
        { id: 'e6', fromId: 'node-mod-services', toId: 'node-kafka-bus', protocol: 'Kafka Wire', bandwidthMbps: 4500, status: 'OPTIMIZED', latencyMs: 6 },
        { id: 'e7', fromId: 'node-db-mainframe', toId: 'node-infra-onprem', protocol: 'SAN Fiber', bandwidthMbps: 1200, status: 'NORMAL', latencyMs: 35 },
        { id: 'e8', fromId: 'node-kafka-bus', toId: 'node-infra-cloud', protocol: 'Cloud Fabric', bandwidthMbps: 8000, status: 'OPTIMIZED', latencyMs: 4 },
      ],
    },
    stakeholders: [
      {
        id: 'sh-cfo-marcus',
        name: 'Marcus Vance',
        title: 'Chief Financial Officer',
        role: 'Capital Allocation & Shareholder Returns',
        avatar: '💼',
        personality: 'Analytical, laser-focused on quarterly margins and OpEx depreciation.',
        bias: 'Demands immediate quantifiable ROI on all IT expenditures.',
        hiddenAgenda: 'Preparing the bank for a secondary debt offering; cannot tolerate sudden OpEx spikes.',
        negotiationTolerance: 50,
        baseTrust: 55,
        decisionWeights: { financialAcumen: 0.65, deliverySpeed: 0.1, architecturalRigor: 0.15, regulatoryCompliance: 0.1 },
        sampleDialogue: {
          greeting: 'Explain to me why we are spending $400K on refactoring when our return on equity is down 20 bps.',
          resistance: 'I will not approve speculative architectural bets without binding OpEx reduction targets.',
          concession: 'Commit to decommissioning legacy mainframe MIPS by Q4, and I will release modernization capital.',
        },
      },
      {
        id: 'sh-vp-priya',
        name: 'Priya Patel',
        title: 'VP of Digital Banking',
        role: 'Product Velocity & Customer Acquisition',
        avatar: '🚀',
        personality: 'Fast-moving, aggressive, customer obsessed.',
        bias: 'Views architectural reviews and governance gates as bureaucratic excuses for delay.',
        hiddenAgenda: 'Needs to launch instantaneous credit line increases before Q3 earnings call to hit executive incentive bonus.',
        negotiationTolerance: 40,
        baseTrust: 60,
        decisionWeights: { financialAcumen: 0.1, deliverySpeed: 0.7, architecturalRigor: 0.05, regulatoryCompliance: 0.15 },
        sampleDialogue: {
          greeting: 'Our customer churn is at 4.2% because the mobile app takes 8 seconds to load accounts.',
          resistance: 'We cannot pause commercial features for another database migration sprint.',
          concession: 'If you isolate the payment service so my squads can deploy weekly, I will advocate for your budget.',
        },
      },
      {
        id: 'sh-cto-elena',
        name: 'Dr. Elena Rostova',
        title: 'Chief Enterprise Architect',
        role: 'Systems Architecture & Technical Governance',
        avatar: '🛡️',
        personality: 'Principled, rigorous, guardian of long-term engineering health.',
        bias: 'Categorically opposes point-to-point shortcuts and dirty database hooks.',
        hiddenAgenda: 'Wants to establish domain-driven design and event sourcing as standard bank policy.',
        negotiationTolerance: 65,
        baseTrust: 65,
        decisionWeights: { financialAcumen: 0.15, deliverySpeed: 0.1, architecturalRigor: 0.6, regulatoryCompliance: 0.15 },
        sampleDialogue: {
          greeting: 'Bypassing the architecture review board is why we had an 8-hour outage last quarter.',
          resistance: 'Writing directly to the core DB2 tables will corrupt the balance reconciliation ledger.',
          concession: 'If you implement the strangler fig pattern with strict schema contracts, I will expedite review approval.',
        },
      },
      {
        id: 'sh-cso-arthur',
        name: 'Arthur Sterling',
        title: 'Chief Risk & Compliance Officer',
        role: 'Regulatory Adherence & Information Security',
        avatar: '⚖️',
        personality: 'Methodical, audit-sensitive, cautious.',
        bias: 'Prioritizes compliance certifications and data privacy over delivery speed.',
        hiddenAgenda: 'Under direct scrutiny by regulatory agency after industry-wide data leak audit.',
        negotiationTolerance: 45,
        baseTrust: 50,
        decisionWeights: { financialAcumen: 0.1, deliverySpeed: 0.05, architecturalRigor: 0.25, regulatoryCompliance: 0.6 },
        sampleDialogue: {
          greeting: 'Regulatory penalties are not hypothetical. They are existential.',
          resistance: 'This cloud migration proposal does not provide hardware encryption isolation for payment secrets.',
          concession: 'Incorporate HSM tokenization and audit logging, and I will sign off on the production clearance.',
        },
      },
    ],
    roundEvents: [
      {
        roundNumber: 1,
        title: 'Q1: Competitor Neobank Instant-Card Launch',
        description: 'Challenger bank "ApexPay" launched instant virtual cards with zero fx fees, pulling away 80,000 younger depositors. Product leadership demands immediate parity.',
        type: 'COMPETITIVE_SURGE',
        severity: 'MEDIUM',
        immediateImpact: { budgetFine: 60, tdiSurge: 6, velocityPenalty: 0 },
        choices: [
          {
            id: 'ev1-shortcut',
            text: 'Hack direct API hooks into the COBOL monolith (Launches in 3 weeks, massive debt)',
            capExImpact: 80,
            tdiImpact: 15,
            velocityImpact: 18,
            trustImpact: { 'sh-vp-priya': 15, 'sh-cto-elena': -15 },
          },
          {
            id: 'ev1-strangler',
            text: 'Deploy an anti-corruption layer & Kafka microservice (4-week delay, sound architecture)',
            capExImpact: 160,
            tdiImpact: -8,
            velocityImpact: -5,
            trustImpact: { 'sh-cto-elena': 14, 'sh-vp-priya': -6, 'sh-cfo-marcus': -4 },
          },
          {
            id: 'ev1-wait',
            text: 'Offer cashback incentives instead of technology changes (Conserves engineering, burns marketing cash)',
            capExImpact: 120,
            tdiImpact: 0,
            velocityImpact: 0,
            trustImpact: { 'sh-cfo-marcus': -10, 'sh-vp-priya': -8 },
          },
        ],
      },
      {
        roundNumber: 2,
        title: 'Q2: Central Bank Regulatory Open Banking Mandate',
        description: 'Banking authorities announce mandatory open-banking API standards with strict 300ms SLA and audit penalties for non-compliance.',
        type: 'AUDIT',
        severity: 'HIGH',
        immediateImpact: { budgetFine: 140, tdiSurge: 0, velocityPenalty: -10 },
        choices: [
          {
            id: 'ev2-modern-gateway',
            text: 'Deploy cloud-native API gateway with Redis rate limiting and automated audit telemetry',
            capExImpact: 210,
            tdiImpact: -12,
            velocityImpact: 10,
            trustImpact: { 'sh-cso-arthur': 20, 'sh-cto-elena': 12, 'sh-cfo-marcus': -8 },
          },
          {
            id: 'ev2-patch-core',
            text: 'Expose legacy MQ endpoints through an unencrypted reverse proxy',
            capExImpact: 70,
            tdiImpact: 12,
            velocityImpact: 0,
            trustImpact: { 'sh-cso-arthur': -18, 'sh-cfo-marcus': 6 },
          },
          {
            id: 'ev2-seek-waiver',
            text: 'Hire regulatory lobbyists to request a 1-year compliance extension',
            capExImpact: 150,
            tdiImpact: 0,
            velocityImpact: 0,
            trustImpact: { 'sh-cso-arthur': -12, 'sh-cfo-marcus': -10 },
          },
        ],
      },
      {
        roundNumber: 3,
        title: 'Q3: Black Friday Transaction Surge & Monolith Deadlock',
        description: 'Simultaneous shopping volume causes DB2 transaction locking. Account balances freeze for 47 minutes during peak evening hours.',
        type: 'CRISIS',
        severity: 'BLACK_SWAN',
        immediateImpact: { budgetFine: 320, tdiSurge: 10, velocityPenalty: -25, downedNodeIds: ['node-legacy-core', 'node-db-mainframe'] },
        choices: [
          {
            id: 'ev3-read-shards',
            text: 'Emergency Strangler: Divert balance read traffic to asynchronous Kafka replicas with circuit breaker',
            capExImpact: 240,
            tdiImpact: -18,
            velocityImpact: 8,
            trustImpact: { 'sh-cto-elena': 18, 'sh-cfo-marcus': -12 },
          },
          {
            id: 'ev3-scale-hardware',
            text: 'Emergency mainframe MIPS lease upgrade (Huge recurring OpEx penalty)',
            capExImpact: 350,
            tdiImpact: 6,
            velocityImpact: -5,
            trustImpact: { 'sh-cfo-marcus': -20, 'sh-vp-priya': 10 },
          },
          {
            id: 'ev3-throttle',
            text: 'Aggressively rate-limit non-essential traffic and queue mobile transactions',
            capExImpact: 50,
            tdiImpact: 2,
            velocityImpact: -18,
            trustImpact: { 'sh-vp-priya': -22, 'sh-cfo-marcus': -6 },
          },
        ],
      },
      {
        roundNumber: 4,
        title: 'Q4: Annual Board Strategy & Modernization Verdict',
        description: 'The Board reviews the bank transformation. Final scorecard evaluates TCO, debt reduction, platform velocity, and reliability.',
        type: 'MARKET_SHIFT',
        severity: 'HIGH',
        immediateImpact: { budgetFine: 0, tdiSurge: 0, velocityPenalty: 0 },
        choices: [
          {
            id: 'ev4-expansion',
            text: 'Showcase modernized microservices and request multi-year cloud transformation tranches',
            capExImpact: 150,
            tdiImpact: -6,
            velocityImpact: 12,
            trustImpact: { 'sh-cfo-marcus': 10, 'sh-vp-priya': 12, 'sh-cto-elena': 15 },
          },
          {
            id: 'ev4-cash-freeze',
            text: 'Implement austerity spending freeze to boast high short-term cash reserves to Wall Street',
            capExImpact: -120,
            tdiImpact: 14,
            velocityImpact: -18,
            trustImpact: { 'sh-cfo-marcus': 20, 'sh-cto-elena': -18, 'sh-vp-priya': -16 },
          },
          {
            id: 'ev4-balanced-close',
            text: 'Maintain existing investment velocity into the next fiscal calendar',
            capExImpact: 0,
            tdiImpact: 0,
            velocityImpact: 0,
            trustImpact: { 'sh-cfo-marcus': 5, 'sh-cto-elena': 5 },
          },
        ],
      },
    ],
    initiativesCatalog: [
      {
        id: 'init-strangler-core',
        name: 'Strangler Fig Core Modernization',
        category: 'MODERNIZATION',
        description: 'Incrementally carve out transactions from the COBOL mainframe to cloud-native microservices.',
        capExCost: 350,
        opExDelta: -45,
        tdiDelta: -24,
        velocityDelta: 16,
        resilienceDelta: 20,
        complianceDelta: 12,
        trustDelta: { 'sh-cto-elena': 16, 'sh-vp-priya': 8, 'sh-cfo-marcus': -6 },
        affectedNodeIds: ['node-legacy-core', 'node-mod-services'],
        durationRounds: 1,
        riskLevel: 'MEDIUM',
      },
      {
        id: 'init-kafka-ledger',
        name: 'Kafka Distributed Financial Ledger',
        category: 'MODERNIZATION',
        description: 'Migrate synchronous batch updates to event-driven streaming architecture.',
        capExCost: 280,
        opExDelta: -25,
        tdiDelta: -18,
        velocityDelta: 14,
        resilienceDelta: 22,
        complianceDelta: 8,
        trustDelta: { 'sh-cto-elena': 14, 'sh-cfo-marcus': -5 },
        affectedNodeIds: ['node-db-mainframe', 'node-kafka-bus'],
        durationRounds: 1,
        riskLevel: 'LOW',
      },
      {
        id: 'init-cloud-mesh',
        name: 'Multi-Region Cloud Mesh Deployment',
        category: 'CLOUD_INFRA',
        description: 'Decommission legacy on-prem datacenter racks and migrate to automated multi-zone Kubernetes.',
        capExCost: 400,
        opExDelta: -55,
        tdiDelta: -16,
        velocityDelta: 15,
        resilienceDelta: 26,
        complianceDelta: 14,
        trustDelta: { 'sh-cfo-marcus': 12, 'sh-cto-elena': 15 },
        affectedNodeIds: ['node-infra-onprem', 'node-infra-cloud'],
        durationRounds: 1,
        riskLevel: 'HIGH',
      },
      {
        id: 'init-shadow-feature-sprint',
        name: 'Bypass Architecture Feature Blitz',
        category: 'FEATURE_EXPEDITE',
        description: 'Hardcode direct database queries and bypass architectural review to push marketing features.',
        capExCost: 150,
        opExDelta: 50,
        tdiDelta: 22,
        velocityDelta: 28,
        resilienceDelta: -18,
        complianceDelta: -22,
        trustDelta: { 'sh-vp-priya': 24, 'sh-cto-elena': -25, 'sh-cso-arthur': -20 },
        affectedNodeIds: ['node-biz-app', 'node-legacy-core'],
        durationRounds: 1,
        riskLevel: 'EXTREME',
      },
      {
        id: 'init-zero-trust-sec',
        name: 'Zero-Trust mTLS & Automated Audit Fabric',
        category: 'SECURITY_COMPLIANCE',
        description: 'Deploy hardware security modules, automated token rotation, and immutable audit logs.',
        capExCost: 220,
        opExDelta: -10,
        tdiDelta: -12,
        velocityDelta: -5,
        resilienceDelta: 18,
        complianceDelta: 32,
        trustDelta: { 'sh-cso-arthur': 28, 'sh-cto-elena': 10, 'sh-vp-priya': -6 },
        affectedNodeIds: ['node-api-gw', 'node-db-mainframe'],
        durationRounds: 1,
        riskLevel: 'LOW',
      },
      {
        id: 'init-ai-ops-copilot',
        name: 'AI Operations & Synthetic Telemetry Sharding',
        category: 'AI_AUTOMATION',
        description: 'Autonomous AI probes detecting database deadlocks and routing traffic dynamically.',
        capExCost: 240,
        opExDelta: -30,
        tdiDelta: -14,
        velocityDelta: 16,
        resilienceDelta: 20,
        complianceDelta: 6,
        trustDelta: { 'sh-cto-elena': 12, 'sh-cfo-marcus': 10, 'sh-vp-priya': 10 },
        affectedNodeIds: ['node-api-gw', 'node-mod-services'],
        durationRounds: 1,
        riskLevel: 'MEDIUM',
      },
    ],
    tags: ['FinTech', 'Core Banking', 'Mainframe Migration', 'PCI-DSS', 'Executive Strategy'],
    author: 'GemSim Enterprise Curators',
    isDefault: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'scen-healthtech-healthnova',
    title: 'HealthNova: Clinical EHR & Telehealth Overhaul',
    industry: 'Healthcare & Life Sciences',
    difficulty: 'EXECUTIVE',
    description: 'Lead a nationwide hospital network through an urgent cloud migration, telehealth scale-up, and strict HIPAA compliance overhaul while maintaining 99.999% clinical uptime.',
    businessContext: 'HealthNova operates 45 regional hospitals. Clinical decisions rely on an on-premise Electronic Health Record (EHR) monolith with 800ms latency. The pandemic accelerated patient telehealth demand by 600%, pushing network infrastructure to near-total collapse.',
    baselineMetrics: {
      tco: 2800,
      budgetRemaining: 1800,
      opEx: 620,
      capExSpent: 500,
      technicalDebtIndex: 66,
      deliveryVelocity: 42,
      stakeholderTrust: 58,
      resilienceIndex: 54,
      complianceScore: 70,
      modernizedNodesCount: 1,
    },
    winLossConditions: {
      maxTechnicalDebtIndex: 40,
      minStakeholderTrustAvg: 65,
      minDeliveryVelocity: 60,
      minResilienceIndex: 80,
      maxTCOBudget: 5500,
      targetCapabilitiesModernized: 4,
    },
    totalRounds: 4,
    topology: {
      nodes: [
        {
          id: 'hn-telehealth',
          name: 'Patient Telehealth & WebRTC Portal',
          layer: 'BUSINESS',
          description: 'Real-time video consultations and patient appointment scheduling.',
          health: 72,
          technicalDebt: 32,
          criticalPath: true,
          costPerRound: 60,
          position: { x: -5, y: 5, z: 0 },
          status: 'HEALTHY',
          dependencies: ['hn-api-gw'],
          telemetry: { latencyMs: 55, throughputRps: 1800, errorRatePercent: 0.3, failureRisk: 20 },
        },
        {
          id: 'hn-ehr-core',
          name: 'Clinical EHR Monolith (Epic/Cerner Legacy)',
          layer: 'APPLICATION',
          description: 'Patient charts, medication dispensing, and clinical laboratory records.',
          health: 46,
          technicalDebt: 78,
          criticalPath: true,
          costPerRound: 210,
          position: { x: 0, y: 2, z: 0 },
          status: 'CRITICAL',
          dependencies: ['hn-db-clinical', 'hn-infra-onprem'],
          telemetry: { latencyMs: 780, throughputRps: 520, errorRatePercent: 3.8, failureRisk: 84 },
        },
        {
          id: 'hn-api-gw',
          name: 'HIPAA Secure FHIR Gateway',
          layer: 'APPLICATION',
          description: 'Fast Healthcare Interoperability Resources (FHIR) API integration broker.',
          health: 84,
          technicalDebt: 20,
          criticalPath: true,
          costPerRound: 45,
          position: { x: -4, y: 2, z: 0 },
          status: 'HEALTHY',
          dependencies: ['hn-ehr-core'],
          telemetry: { latencyMs: 22, throughputRps: 3200, errorRatePercent: 0.05, failureRisk: 12 },
        },
        {
          id: 'hn-db-clinical',
          name: 'Central Patient Records Store',
          layer: 'DATA',
          description: 'Tightly coupled relational database containing 35 million clinical histories.',
          health: 50,
          technicalDebt: 74,
          criticalPath: true,
          costPerRound: 130,
          position: { x: 0, y: -2, z: 0 },
          status: 'DEGRADED',
          dependencies: ['hn-infra-onprem'],
          telemetry: { latencyMs: 510, throughputRps: 820, errorRatePercent: 2.2, failureRisk: 70 },
        },
        {
          id: 'hn-infra-onprem',
          name: 'Hospital Campus Datacenters',
          layer: 'INFRASTRUCTURE',
          description: 'Distributed on-prem servers across 45 hospitals with inconsistent patching.',
          health: 55,
          technicalDebt: 65,
          criticalPath: true,
          costPerRound: 140,
          position: { x: 0, y: -5, z: 0 },
          status: 'DEGRADED',
          dependencies: [],
          telemetry: { latencyMs: 120, throughputRps: 2800, errorRatePercent: 1.1, failureRisk: 52 },
        },
      ],
      edges: [
        { id: 'he1', fromId: 'hn-telehealth', toId: 'hn-api-gw', protocol: 'WebRTC / HTTPS', bandwidthMbps: 2000, status: 'NORMAL', latencyMs: 25 },
        { id: 'he2', fromId: 'hn-api-gw', toId: 'hn-ehr-core', protocol: 'HL7 / FHIR', bandwidthMbps: 500, status: 'BOTTLENECK', latencyMs: 380 },
        { id: 'he3', fromId: 'hn-ehr-core', toId: 'hn-db-clinical', protocol: 'ODBC Connection Pool', bandwidthMbps: 600, status: 'BOTTLENECK', latencyMs: 440 },
        { id: 'he4', fromId: 'hn-db-clinical', toId: 'hn-infra-onprem', protocol: 'Fiber SAN', bandwidthMbps: 1000, status: 'NORMAL', latencyMs: 40 },
      ],
    },
    stakeholders: [
      {
        id: 'sh-cmo-sarah',
        name: 'Dr. Sarah Lin',
        title: 'Chief Medical Officer',
        role: 'Clinical Care & Patient Safety',
        avatar: '🩺',
        personality: 'Patient-centric, fiercely protective of doctor workflow and clinical uptime.',
        bias: 'Zero patience for IT disruptions during surgical or inpatient hours.',
        hiddenAgenda: 'Championing physician satisfaction to reduce clinician burnout.',
        negotiationTolerance: 45,
        baseTrust: 65,
        decisionWeights: { financialAcumen: 0.1, deliverySpeed: 0.3, architecturalRigor: 0.3, regulatoryCompliance: 0.3 },
        sampleDialogue: {
          greeting: 'A system crash in the emergency room is not a ticket. It is a patient risk.',
          resistance: 'Do not touch the clinical charting interface unless you can guarantee zero downtime.',
          concession: 'If the telehealth integration saves our physicians 20 minutes per shift, you have my support.',
        },
      },
      {
        id: 'sh-cio-david',
        name: 'David Thornton',
        title: 'Chief Information Officer',
        role: 'Healthcare Enterprise Architecture',
        avatar: '🏥',
        personality: 'Careful, experienced, risk-averse enterprise strategist.',
        bias: 'Believes in proven vendor platforms over experimental home-grown microservices.',
        hiddenAgenda: 'Navigating impending Joint Commission and HIPAA federal audits.',
        negotiationTolerance: 55,
        baseTrust: 55,
        decisionWeights: { financialAcumen: 0.25, deliverySpeed: 0.15, architecturalRigor: 0.35, regulatoryCompliance: 0.25 },
        sampleDialogue: {
          greeting: 'We manage life-critical infrastructure. Stability precedes innovation.',
          resistance: 'Migrating clinical records to public cloud without end-to-end BAA agreements is non-viable.',
          concession: 'Deliver a validated FHIR API bridge, and we can greenlight the telehealth scale-up.',
        },
      },
    ],
    roundEvents: [
      {
        roundNumber: 1,
        title: 'Q1: Telehealth Surges 400% Under Regional Flu Wave',
        description: 'Emergency department influx leads to unprecedented video consultation volume, causing network packet loss.',
        type: 'DISRUPTION',
        severity: 'HIGH',
        immediateImpact: { budgetFine: 80, tdiSurge: 5, velocityPenalty: -10 },
        choices: [
          { id: 'he-c1', text: 'Spin up cloud WebRTC edge proxies (Fast relief)', capExImpact: 120, tdiImpact: -5, velocityImpact: 10, trustImpact: { 'sh-cmo-sarah': 15 } },
          { id: 'he-c2', text: 'Queue patient video calls (Frustrates clinicians)', capExImpact: 20, tdiImpact: 2, velocityImpact: -15, trustImpact: { 'sh-cmo-sarah': -18 } },
        ],
      },
      {
        roundNumber: 2,
        title: 'Q2: Surprise HIPAA Office of Civil Rights Audit',
        description: 'Federal auditors request access logs and encryption validation across on-premise hospital datacenters.',
        type: 'AUDIT',
        severity: 'HIGH',
        immediateImpact: { budgetFine: 150, tdiSurge: 0, velocityPenalty: -12 },
        choices: [
          { id: 'he-c3', text: 'Execute emergency zero-trust encryption and audit telemetry', capExImpact: 190, tdiImpact: -10, velocityImpact: 5, trustImpact: { 'sh-cio-david': 18 } },
          { id: 'he-c4', text: 'Accept consent decree and pay settlement fine', capExImpact: 240, tdiImpact: 4, velocityImpact: 0, trustImpact: { 'sh-cio-david': -15 } },
        ],
      },
      {
        roundNumber: 3,
        title: 'Q3: Ransomware Infiltration Attempt on Campus Hospital',
        description: 'Phishing attack attempts lateral movement toward legacy EHR database.',
        type: 'CRISIS',
        severity: 'BLACK_SWAN',
        immediateImpact: { budgetFine: 220, tdiSurge: 8, velocityPenalty: -18, downedNodeIds: ['hn-infra-onprem'] },
        choices: [
          { id: 'he-c5', text: 'Isolate campus network and activate cloud immutable backups', capExImpact: 180, tdiImpact: -12, velocityImpact: 6, trustImpact: { 'sh-cmo-sarah': 10, 'sh-cio-david': 15 } },
          { id: 'he-c6', text: 'Pay ransom negotiator fee (High liability)', capExImpact: 350, tdiImpact: 10, velocityImpact: -10, trustImpact: { 'sh-cio-david': -25 } },
        ],
      },
      {
        roundNumber: 4,
        title: 'Q4: Integrated Clinical Network Board Review',
        description: 'Final review of patient satisfaction, system resilience, and operating margins.',
        type: 'MARKET_SHIFT',
        severity: 'MEDIUM',
        immediateImpact: { budgetFine: 0, tdiSurge: 0, velocityPenalty: 0 },
        choices: [
          { id: 'he-c7', text: 'Present unified clinical digital health platform results', capExImpact: 80, tdiImpact: -4, velocityImpact: 8, trustImpact: { 'sh-cmo-sarah': 12, 'sh-cio-david': 12 } },
          { id: 'he-c8', text: 'Defer further modernization to build hospital endowment', capExImpact: -100, tdiImpact: 8, velocityImpact: -12, trustImpact: { 'sh-cmo-sarah': -14 } },
        ],
      },
    ],
    initiativesCatalog: [
      {
        id: 'h-init-fhir',
        name: 'FHIR Interoperability & Decoupled APIs',
        category: 'MODERNIZATION',
        description: 'Modern FHIR standard API layer insulating the EHR monolith from modern patient apps.',
        capExCost: 310,
        opExDelta: -30,
        tdiDelta: -20,
        velocityDelta: 16,
        resilienceDelta: 18,
        complianceDelta: 24,
        trustDelta: { 'sh-cio-david': 16, 'sh-cmo-sarah': 10 },
        affectedNodeIds: ['hn-api-gw', 'hn-ehr-core'],
        durationRounds: 1,
        riskLevel: 'LOW',
      },
      {
        id: 'h-init-cloud-ehr',
        name: 'HIPAA-Compliant Cloud EHR Migration',
        category: 'CLOUD_INFRA',
        description: 'Decommission aging hospital server rooms and migrate records to dedicated cloud health instances.',
        capExCost: 420,
        opExDelta: -50,
        tdiDelta: -22,
        velocityDelta: 14,
        resilienceDelta: 25,
        complianceDelta: 20,
        trustDelta: { 'sh-cio-david': 18, 'sh-cmo-sarah': 8 },
        affectedNodeIds: ['hn-infra-onprem', 'hn-db-clinical'],
        durationRounds: 1,
        riskLevel: 'HIGH',
      },
      {
        id: 'h-init-bypass',
        name: 'Emergency Direct EHR Database Query Scripts',
        category: 'FEATURE_EXPEDITE',
        description: 'Hardcode direct database queries to expedite clinical research reports without architectural gating.',
        capExCost: 90,
        opExDelta: 40,
        tdiDelta: 20,
        velocityDelta: 22,
        resilienceDelta: -16,
        complianceDelta: -28,
        trustDelta: { 'sh-cmo-sarah': 14, 'sh-cio-david': -24 },
        affectedNodeIds: ['hn-ehr-core', 'hn-db-clinical'],
        durationRounds: 1,
        riskLevel: 'EXTREME',
      },
    ],
    tags: ['Healthcare', 'HIPAA', 'EHR Monolith', 'Telehealth', 'Clinical Resilience'],
    author: 'GemSim Healthcare Working Group',
    isDefault: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'scen-offshore-mirage',
    title: 'Mirage Offshore : Arbitrage Coûts, Souveraineté et Dette Technique',
    industry: 'Grande Entreprise de Services / Assurance et Fintech',
    difficulty: 'EXECUTIVE',
    description: 'Arbitrage stratégique entre réduction des coûts via l\'externalisation et préservation du patrimoine architectural, de la souveraineté des données et des compétences internes.',
    businessContext: 'La direction générale impose une réduction de 35% de l\'OpEx IT via un contrat cadre avec une ESN offshore. Les équipes internes tirent la sonnette d\'alarme sur l\'hémorragie de compétences, la duplication de code et la perte de maîtrise du socle applicatif souverain.',
    baselineMetrics: {
      tco: 3200,
      budgetRemaining: 1800,
      opEx: 680,
      capExSpent: 450,
      technicalDebtIndex: 68,
      deliveryVelocity: 46,
      stakeholderTrust: 55,
      resilienceIndex: 52,
      complianceScore: 68,
      modernizedNodesCount: 2,
    },
    winLossConditions: {
      maxTechnicalDebtIndex: 42,
      minStakeholderTrustAvg: 65,
      minDeliveryVelocity: 62,
      minResilienceIndex: 78,
      maxTCOBudget: 5800,
      targetCapabilitiesModernized: 4,
    },
    totalRounds: 4,
    topology: {
      nodes: [
        {
          id: 'node-offshore-center',
          name: 'Offshore Delivery Center',
          layer: 'APPLICATION',
          description: 'Pôle de développement externalisé en régie/forfait avec forte rotation d\'ingénieurs et décalage horaire.',
          health: 48,
          technicalDebt: 72,
          criticalPath: true,
          costPerRound: 75,
          position: { x: -8.5, y: 0, z: 2.5 },
          status: 'CRITICAL',
          dependencies: ['node-dev-pipeline'],
          telemetry: { latencyMs: 290, throughputRps: 720, errorRatePercent: 3.6, failureRisk: 74 },
        },
        {
          id: 'node-reg-reporting',
          name: 'Regulatory Reporting',
          layer: 'DATA',
          description: 'Moteur de conformité réglementaire (DORA, RGPD, ACPR) alimenté par les données de transaction.',
          health: 72,
          technicalDebt: 34,
          criticalPath: false,
          costPerRound: 45,
          position: { x: -7.5, y: 0, z: -2.5 },
          status: 'HEALTHY',
          dependencies: ['node-core-logic'],
          telemetry: { latencyMs: 80, throughputRps: 1100, errorRatePercent: 0.1, failureRisk: 22 },
        },
        {
          id: 'node-dev-pipeline',
          name: 'Dev Pipeline',
          layer: 'APPLICATION',
          description: 'Pipeline CI/CD transfrontalier avec validation automatisée des pull requests et contrôle des dépendances.',
          health: 58,
          technicalDebt: 55,
          criticalPath: true,
          costPerRound: 50,
          position: { x: -4.0, y: 0, z: 0.5 },
          status: 'DEGRADED',
          dependencies: ['node-arch-guardrail'],
          telemetry: { latencyMs: 45, throughputRps: 3400, errorRatePercent: 0.8, failureRisk: 40 },
        },
        {
          id: 'node-arch-guardrail',
          name: 'Architecture Guardrail',
          layer: 'APPLICATION',
          description: 'Passerelle de gouvernance mTLS, contrats d\'interface stricts et revue d\'architecture automatique.',
          health: 82,
          technicalDebt: 22,
          criticalPath: true,
          costPerRound: 40,
          position: { x: 0.0, y: 0, z: 0.0 },
          status: 'HEALTHY',
          dependencies: ['node-onshore-eng', 'node-core-logic'],
          telemetry: { latencyMs: 18, throughputRps: 4600, errorRatePercent: 0.02, failureRisk: 10 },
        },
        {
          id: 'node-knowledge-base',
          name: 'Knowledge Base',
          layer: 'DATA',
          description: 'Référentiel de documentation d\'architecture, cartographie des flux et standards de développement.',
          health: 55,
          technicalDebt: 60,
          criticalPath: false,
          costPerRound: 35,
          position: { x: 2.8, y: 0, z: 2.6 },
          status: 'DEGRADED',
          dependencies: ['node-onshore-eng'],
          telemetry: { latencyMs: 95, throughputRps: 850, errorRatePercent: 0.4, failureRisk: 36 },
        },
        {
          id: 'node-onshore-eng',
          name: 'Onshore Engineering',
          layer: 'BUSINESS',
          description: 'Équipes d\'ingénierie et d\'architecture internes garantes du savoir-faire métier et de l\'innovation.',
          health: 72,
          technicalDebt: 38,
          criticalPath: true,
          costPerRound: 90,
          position: { x: 5.6, y: 0, z: -1.8 },
          status: 'HEALTHY',
          dependencies: ['node-core-logic'],
          telemetry: { latencyMs: 25, throughputRps: 1500, errorRatePercent: 0.05, failureRisk: 18 },
        },
        {
          id: 'node-core-logic',
          name: 'Core Business Logic',
          layer: 'APPLICATION',
          description: 'Socle applicatif souverain regroupant les règles métier de souscription, de tarification et de sinistres.',
          health: 50,
          technicalDebt: 65,
          criticalPath: true,
          costPerRound: 120,
          position: { x: 8.8, y: 0, z: 0.5 },
          status: 'DEGRADED',
          dependencies: ['node-data-vault'],
          telemetry: { latencyMs: 340, throughputRps: 920, errorRatePercent: 1.8, failureRisk: 66 },
        },
        {
          id: 'node-data-vault',
          name: 'Sensitive Data Vault',
          layer: 'DATA',
          description: 'Coffre-fort de données souveraines sous confinement juridique strict (données clients et bancaires).',
          health: 78,
          technicalDebt: 28,
          criticalPath: true,
          costPerRound: 85,
          position: { x: 11.0, y: 0, z: -2.8 },
          status: 'HEALTHY',
          dependencies: [],
          telemetry: { latencyMs: 70, throughputRps: 2100, errorRatePercent: 0.05, failureRisk: 16 },
        },
      ],
      edges: [
        { id: 'mo-e1', fromId: 'node-dev-pipeline', toId: 'node-offshore-center', protocol: 'mTLS', bandwidthMbps: 1000, latencyMs: 250, status: 'BOTTLENECK' },
        { id: 'mo-e2', fromId: 'node-dev-pipeline', toId: 'node-arch-guardrail', protocol: 'HTTPS', bandwidthMbps: 2500, latencyMs: 40, status: 'OPTIMIZED' },
        { id: 'mo-e3', fromId: 'node-arch-guardrail', toId: 'node-onshore-eng', protocol: 'gRPC', bandwidthMbps: 5000, latencyMs: 15, status: 'OPTIMIZED' },
        { id: 'mo-e4', fromId: 'node-arch-guardrail', toId: 'node-core-logic', protocol: 'REST', bandwidthMbps: 1500, latencyMs: 120, status: 'BOTTLENECK' },
        { id: 'mo-e5', fromId: 'node-onshore-eng', toId: 'node-knowledge-base', protocol: 'HTTPS', bandwidthMbps: 1000, latencyMs: 30, status: 'NORMAL' },
        { id: 'mo-e6', fromId: 'node-core-logic', toId: 'node-data-vault', protocol: 'TCP/TLS', bandwidthMbps: 4000, latencyMs: 20, status: 'OPTIMIZED' },
        { id: 'mo-e7', fromId: 'node-core-logic', toId: 'node-reg-reporting', protocol: 'Kafka', bandwidthMbps: 2000, latencyMs: 60, status: 'NORMAL' },
      ],
    },
    stakeholders: [
      {
        id: 'sh-cfo-julien',
        name: 'Julien Marchand',
        title: 'Directeur Financier (CFO)',
        role: 'Optimisation Budgétaire & Rentabilité',
        avatar: '💼',
        personality: 'Focalisé sur la réduction drastique des coûts et le respect de la trajectoire budgétaire.',
        bias: 'Considère le développement offshore comme le levier prioritaire de compression des dépenses.',
        hiddenAgenda: 'Obtenir une prime sur objectif en atteignant 35% d\'économies sur la masse salariale IT.',
        negotiationTolerance: 45,
        baseTrust: 50,
        decisionWeights: { financialAcumen: 0.7, deliverySpeed: 0.15, architecturalRigor: 0.05, regulatoryCompliance: 0.1 },
        sampleDialogue: {
          greeting: 'Notre ratio d\'exploitation est sous pression. L\'arbitrage offshore n\'est pas négociable.',
          resistance: 'Tout rapatriement de charge onshore doit être autofinancé par des gains de productivité immédiats.',
          concession: 'Si vous prouvez que les revues de code réduisent les pénalités contractuelles, je débloque un budget d\'outillage.',
        },
      },
      {
        id: 'sh-arch-claire',
        name: 'Claire Vasseur',
        title: 'Directrice de l\'Architecture d\'Entreprise',
        role: 'Gouvernance & Souveraineté Technologique',
        avatar: '🛡️',
        personality: 'Rigoureuse, intransigeante sur les standards et la pérennité du patrimoine logiciel.',
        bias: 'Opposée à l\'externalisation massive sans sas de contrôle d\'architecture et documentation stricte.',
        hiddenAgenda: 'Sanctuariser le coeur métier et réinternaliser les compétences d\'ingénierie stratégiques.',
        negotiationTolerance: 65,
        baseTrust: 65,
        decisionWeights: { financialAcumen: 0.1, deliverySpeed: 0.15, architecturalRigor: 0.6, regulatoryCompliance: 0.15 },
        sampleDialogue: {
          greeting: 'L\'offshore sans garde-fous produit du code jetable et une dette technique ingérable.',
          resistance: 'Accorder des accès directs à la base de données au prestataire viole notre politique de souveraineté.',
          concession: 'Mettons en place une passerelle API stricte et des revues paritaires avant toute mise en production.',
        },
      },
      {
        id: 'sh-esn-rajesh',
        name: 'Rajesh Sharma',
        title: 'Directeur de Compte ESN Offshore',
        role: 'Engagement de Service & Delivery Tiers',
        avatar: '🌐',
        personality: 'Diplomate, orienté volume et respect des jalons contractuels.',
        bias: 'Privilégie le respect des délais et la rentabilité du forfait au détriment de l\'adhérence fine aux standards.',
        hiddenAgenda: 'Maximiser le volume d\'heures facturables et convertir les anomalies en avenants payants.',
        negotiationTolerance: 50,
        baseTrust: 55,
        decisionWeights: { financialAcumen: 0.25, deliverySpeed: 0.55, architecturalRigor: 0.1, regulatoryCompliance: 0.1 },
        sampleDialogue: {
          greeting: 'Mes équipes sont mobilisées 24/7 pour livrer le sprint conformément au cahier des charges.',
          resistance: 'Si les spécifications changent ou que les revues bloquent les releases, nous devrons émettre un avenant.',
          concession: 'Nous acceptons d\'intégrer un lead architecte dédié à vos quality gates sans surcoût.',
        },
      },
    ],
    roundEvents: [
      {
        roundNumber: 1,
        title: 'Q1 : Choc de Communication & Friction Culturelle',
        description: 'La première release majeure développée offshore présente un taux de non-conformité de 42% aux standards d\'architecture. Les équipes internes refusent de déployer.',
        type: 'CRISIS',
        severity: 'HIGH',
        immediateImpact: { budgetFine: 80, tdiSurge: 10, velocityPenalty: 12 },
        choices: [
          {
            id: 'mo-q1-c1',
            text: 'Mettre en place des Quality Gates automatisées et un sas de validation paritaire',
            capExImpact: 75,
            tdiImpact: -8,
            velocityImpact: -5,
            trustImpact: { 'sh-arch-claire': 12, 'sh-cfo-julien': -4, 'sh-esn-rajesh': 6 },
            nodeHealthImpacts: { 'node-arch-guardrail': 25, 'node-dev-pipeline': 20 },
          },
          {
            id: 'mo-q1-c2',
            text: 'Forcer la mise en production pour respecter l\'échéance commerciale du CFO',
            capExImpact: 20,
            tdiImpact: 14,
            velocityImpact: 10,
            trustImpact: { 'sh-cfo-julien': 10, 'sh-arch-claire': -18, 'sh-esn-rajesh': 8 },
            nodeHealthImpacts: { 'node-core-logic': -20 },
          },
        ],
      },
      {
        roundNumber: 2,
        title: 'Q2 : Fuite de Données de Test & Audit Réglementaire',
        description: 'Des données clients de production ont été copiées dans l\'environnement de staging distant sans anonymisation préalable.',
        type: 'AUDIT',
        severity: 'BLACK_SWAN',
        immediateImpact: { budgetFine: 160, tdiSurge: 8, velocityPenalty: 15 },
        choices: [
          {
            id: 'mo-q2-c1',
            text: 'Déployer une plateforme de génération de données de synthèse et durcir le sas API',
            capExImpact: 120,
            tdiImpact: -6,
            velocityImpact: -8,
            trustImpact: { 'sh-arch-claire': 14, 'sh-cfo-julien': -8 },
            nodeHealthImpacts: { 'node-data-vault': 30 },
          },
          {
            id: 'mo-q2-c2',
            text: 'Signer un avenant de non-divulgation renforcé avec l\'ESN sans refonte technique',
            capExImpact: 40,
            tdiImpact: 8,
            velocityImpact: 0,
            trustImpact: { 'sh-cfo-julien': 6, 'sh-arch-claire': -14 },
            nodeHealthImpacts: {},
          },
        ],
      },
      {
        roundNumber: 3,
        title: 'Q3 : Turnover Critique au Centre Distant',
        description: '70% de l\'équipe offshore quitte le projet en 2 mois, entraînant une perte sèche de la connaissance tacite du code.',
        type: 'DISRUPTION',
        severity: 'HIGH',
        immediateImpact: { budgetFine: 50, tdiSurge: 12, velocityPenalty: 20 },
        choices: [
          {
            id: 'mo-q3-c1',
            text: 'Financer des sessions de pair-programming onshore/offshore et sanctuariser la documentation',
            capExImpact: 90,
            tdiImpact: -10,
            velocityImpact: -6,
            trustImpact: { 'sh-arch-claire': 10, 'sh-esn-rajesh': 12 },
            nodeHealthImpacts: { 'node-knowledge-base': 35 },
          },
          {
            id: 'mo-q3-c2',
            text: 'Exiger le remplacement immédiat des effectifs sous astreinte contractuelle',
            capExImpact: 10,
            tdiImpact: 12,
            velocityImpact: -15,
            trustImpact: { 'sh-esn-rajesh': -16, 'sh-cfo-julien': 4 },
            nodeHealthImpacts: { 'node-offshore-center': -25 },
          },
        ],
      },
      {
        roundNumber: 4,
        title: 'Q4 : Arbitrage de Renouvellement Contractuel',
        description: 'Le contrat triennal de sous-traitance arrive à échéance. La direction générale attend la recommandation stratégique finale.',
        type: 'MARKET_SHIFT',
        severity: 'MEDIUM',
        immediateImpact: { budgetFine: 0, tdiSurge: 0, velocityPenalty: 0 },
        choices: [
          {
            id: 'mo-q4-c1',
            text: 'Modèle Hybride Souverain : Réinternaliser le socle stratégique et confier les commodités à l\'ESN sous SLA stricts',
            capExImpact: 150,
            tdiImpact: -18,
            velocityImpact: 14,
            trustImpact: { 'sh-arch-claire': 18, 'sh-cfo-julien': 10, 'sh-esn-rajesh': 8 },
            nodeHealthImpacts: { 'node-onshore-eng': 30, 'node-core-logic': 25 },
          },
          {
            id: 'mo-q4-c2',
            text: '100% Offshore : Transférer l\'intégralité des périmètres pour maximiser l\'économie faciale',
            capExImpact: 30,
            tdiImpact: 22,
            velocityImpact: -10,
            trustImpact: { 'sh-cfo-julien': 16, 'sh-arch-claire': -25, 'sh-esn-rajesh': 15 },
            nodeHealthImpacts: { 'node-core-logic': -35 },
          },
        ],
      },
    ],
    initiativesCatalog: [
      {
        id: 'mo-init-guardrail',
        name: 'Passerelle de Contrôle & Quality Gates Automatisées',
        category: 'GOVERNANCE_STRICT',
        description: 'Déploiement de SonarQube, de contrats d\'API stricts (OpenAPI/mTLS) et de revues obligatoires par les architectes onshore.',
        capExCost: 220,
        opExDelta: -30,
        tdiDelta: -16,
        velocityDelta: -4,
        resilienceDelta: 20,
        complianceDelta: 18,
        trustDelta: { 'sh-arch-claire': 16, 'sh-cfo-julien': -4 },
        affectedNodeIds: ['node-arch-guardrail', 'node-dev-pipeline'],
        durationRounds: 1,
        riskLevel: 'LOW',
      },
      {
        id: 'mo-init-kb',
        name: 'Plateforme de Documentation & Cartographie Vivante',
        category: 'DEBT_REDUCTION',
        description: 'Capitalisation de la connaissance métier et documentation de l\'architecture applicative pour contrer le turnover.',
        capExCost: 140,
        opExDelta: -15,
        tdiDelta: -10,
        velocityDelta: 8,
        resilienceDelta: 14,
        complianceDelta: 12,
        trustDelta: { 'sh-arch-claire': 12, 'sh-esn-rajesh': 8 },
        affectedNodeIds: ['node-knowledge-base', 'node-onshore-eng'],
        durationRounds: 1,
        riskLevel: 'LOW',
      },
      {
        id: 'mo-init-reinsource',
        name: 'Réinternalisation Ciblée du Coeur Métier Souverain',
        category: 'MODERNIZATION',
        description: 'Recrutement de 8 ingénieurs et architectes seniors onshore pour reprendre la maîtrise des règles de calcul et de tarification.',
        capExCost: 380,
        opExDelta: 60,
        tdiDelta: -24,
        velocityDelta: 16,
        resilienceDelta: 28,
        complianceDelta: 15,
        trustDelta: { 'sh-arch-claire': 22, 'sh-cfo-julien': -14 },
        affectedNodeIds: ['node-core-logic', 'node-onshore-eng'],
        durationRounds: 2,
        riskLevel: 'MEDIUM',
      },
      {
        id: 'mo-init-bypass',
        name: 'Fast-Track Offshore Direct DB Writes',
        category: 'FEATURE_EXPEDITE',
        description: 'Autoriser l\'ESN à insérer directement les écritures dans la base de données sans passer par la passerelle de validation.',
        capExCost: 60,
        opExDelta: 45,
        tdiDelta: 25,
        velocityDelta: 24,
        resilienceDelta: -22,
        complianceDelta: -30,
        trustDelta: { 'sh-cfo-julien': 15, 'sh-arch-claire': -28, 'sh-esn-rajesh': 12 },
        affectedNodeIds: ['node-core-logic', 'node-data-vault'],
        durationRounds: 1,
        riskLevel: 'EXTREME',
      },
    ],
    tags: ['Offshore', 'Souveraineté', 'Architecture Guardrail', 'Dette Technique', 'Arbitrage Coûts'],
    author: 'GemSim Strategic Architecture Council',
    isDefault: true,
    createdAt: new Date().toISOString(),
  },
];
